### ISSUE TITLE
When we will be able to run it locally ? 

### ISSUE THREAD

**Issue by 2blackbar** [CompVis/stable-diffusion#1]
Hey i have gtx1080ti , will the 1024 model run on it or im getting hopes up?
Im using discord SD bot currently but would love to try inpainting.

**Comment by Utopiah** [comment]
Indeed, would be nice to have a `Dockerfile` then interfaces like gradio or even the entire setup via cog being able to integrate with other tools, e.g Gimp, Krita via their plugin system or even tools for children e.g Scratch.

**Comment by litevxx** [comment]
> Hey i have gtx1080ti , will the 1024 model run on it or im getting hopes up? Im using discord SD bot currently but would love to try inpainting.

Going by VRAM, the 512 model will run. We don't currently know how large the 1024 model is, but if it's the same size it should run too.

**Comment by Luffffffy** [comment]
When is the model expected to be available for download，Expecting!!!

**Comment by Iuryck** [comment]
Gonna comment here to follow

**Comment by bibyts** [comment]
What's the link to Discord Stable Diffusion bot?

**Comment by melMass** [comment]
> Discord Stable Diffusion bot

Stable Diffusion is entirely free, but if you aren’t already in the Discord server, you can’t join.

**Comment by johndpope** [comment]
@Utopiah - fyi Dockerfile - https://github.com/CompVis/stable-diffusion/pull/24

**Comment by Utopiah** [comment]
Thanks @johndpope, just waiting for the open source / freely accessible weights now then.

**Comment by breadbrowser** [comment]
> Thanks @johndpope, just waiting for the open source / freely accessible weights now then.

they will most likely will not. Yahoo hasn't made their yahoo answer dataset public

**Comment by nathanshipley** [comment]
> > Thanks @johndpope, just waiting for the open source / freely accessible weights now then.
> 
> they will most likely will not.

They will. The weights have already been released for researchers already and will be released to the public "soon."  Emad talks about this pretty constantly: https://twitter.com/EMostaque/status/1559588668637122561

**Comment by Utopiah** [comment]
@SirFrasi do you have information contradicting https://github.com/huggingface/diffusers/releases/tag/v0.2.3 availability today?

**Comment by Utopiah** [comment]
Now we can, see https://huggingface.co/CompVis

**Comment by bibyts** [comment]
I'm a little confused. I went to this link and downloaded the file but it didn't download a .ckpt file in Gitbash: https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/raw/main/sd-v1-4.ckpt

Where can I find the .ckpt file to use? I was trying to download the oid sha256 from the link above:
oid sha256:fe4efff1e174c627256e44ec2991ba279b3816e364b49f9be2abc0b3ff3f8556

**Comment by hcrawfdev** [comment]
@bibyts 
Do you have git-lfs installed?
https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage
After you do, you should be able to run `git clone https://huggingface.co/CompVis/stable-diffusion-v-1-4-original` and it will include the large .ckpt file.

**Comment by Utopiah** [comment]
> I went to this link and downloaded the file but it didn't download a .ckpt file in Gitbash: https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/raw/main/sd-v1-4.ckpt

@bibyts you can find it on https://huggingface.co/CompVis/stable-diffusion-v-1-4-original/tree/main and use the web interface to download it. As mentioned in the ReadMe you need a HuggingFace account to accept the license.

**Comment by karray** [comment]
Do I have to use the `sd-v1-4.ckpt` weights for the [inpaint.py](https://github.com/CompVis/stable-diffusion/blob/main/scripts/inpaint.py) example?

**Comment by breadbrowser** [comment]
demo here https://huggingface.co/spaces/stabilityai/stable-diffusion

**Comment by Utopiah** [comment]
@breadbrowser that's not local.

**Comment by wolfgangmeyers** [comment]
> Do I have to use the `sd-v1-4.ckpt` weights for the [inpaint.py](https://github.com/CompVis/stable-diffusion/blob/main/scripts/inpaint.py) example?

I think this is a different model that doesn't have the weights released yet.

**Comment by breadbrowser** [comment]
> @breadbrowser that's not local.

but it does run

**Comment by karray** [comment]
> I think this is a different model that doesn't have the weights released yet.

I handled it. [Here](https://github.com/CompVis/stable-diffusion/issues/17#issuecomment-1224165074) is what I did.

**Comment by wolfgangmeyers** [comment]
> > I think this is a different model that doesn't have the weights released yet.
> 
> I handled it. [Here](https://github.com/CompVis/stable-diffusion/issues/17#issuecomment-1224165074) is what I did.

Oh nice. Going to test this out. Wonder if there will be another version that allows text guidance.

**Comment by SirFrasi** [comment]
> @SirFrasi do you have information contradicting https://github.com/huggingface/diffusers/releases/tag/v0.2.3 availability today?

My mistake, I didn't mean stable diffusion per se but, the discord project from stability ai, which now only works with credits at dreamstudio

**Comment by Utopiah** [comment]
> > @breadbrowser that's not local.
> 
> but it does run without error and hassle

Ok and that's useful but this issue, issue #1 is specifically about it being run **locally**.

**Comment by TechnologyClassroom** [comment]
This issue can be closed.  The models were [released through huggingface](https://github.com/huggingface/diffusers/releases/tag/v0.2.3) last week.

**Comment by breadbrowser** [comment]
> > > @breadbrowser that's not local.
> > 
> > 
> > but it does run without error and hassle
> 
> Ok and that's useful but this issue, issue #1 is specifically about it being run **locally**.

kaggle.com
