### ISSUE TITLE
n_samples --1 returns two samples

### ISSUE THREAD

**Issue by terekita** [CompVis/stable-diffusion#11]
`txt2img.py --n_samples 1 ' returns two samples...

Just realizing that number of samples actually returned is double whatever the argument is

**Comment by RafailFridman** [comment]
Check `n_iter` parameter - it is 2 by default. 
`n_samples` is a batch size, `n_iter` is the number of times you want to generate `n_samples` images

**Comment by Alkeryn** [comment]
@RafailFridman does n_samples affect quality ?

**Comment by RafailFridman** [comment]
`n_samples` parameter is just the batch size - how many images in one pass it will generate.
It should not affect the quality of an individual image

**Comment by Alkeryn** [comment]
@RafailFridman Oh i see, thanks !

**Comment by 0x2b3bfa0** [comment]
![](https://asset.cml.dev/48fca3b28053877b96349e0aba9bc42aed30a3eb?cml=png&cache-bypass=62b1b178-e80d-4677-ae34-a7195658e7c9)
