### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '!'

### ISSUE THREAD

**Issue by NicolasH2** [CompVis/stable-diffusion#116]
Hi, I received the error upon trying to use stable-diffusion for the first time.
I ran the example sampling code and got the error message below
```
python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms 

Global seed set to 42
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Traceback (most recent call last):
  File "scripts/txt2img.py", line 344, in <module>
    main()
  File "scripts/txt2img.py", line 240, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts/txt2img.py", line 50, in load_model_from_config
    pl_sd = torch.load(ckpt, map_location="cpu")
  File "D:\Programs\Anaconda3\envs\ldm\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\Programs\Anaconda3\envs\ldm\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '!'.
```

I am working on Windows 10, conda 4.6.11, Python 3.8.5

----------------------------------------------------------------
FYI, for installation I followed the steps from the github page. These are my steps:
```
git pull https://github.com/CompVis/stable-diffusion
cd stable-diffustion
conda env create -f environment.yaml
conda activate ldm
```
then I downloaded sd-v1-4.ckpt from https://huggingface.co/CompVis/stable-diffusion-v-1-4-original
and created the link
```
ln -s sd-v1-4.ckpt models/ldm/stable-diffusion-v1/model.ckpt
```
after that I tried to run the stable-diffusion.

**Comment by patrickvonplaten** [comment]
Hmm it looks like the checkpoint you downloaded is corrupted, could you try downloading it again?

**Comment by NicolasH2** [comment]
thanks, I downloaded it again, and the same error appears. At this point I cannot troubleshoot due to internet-connection issues and personal time limitations.

**Comment by dali-does** [comment]
I had the same problem, and realised that I was on a new machine where `git lfs` was not installed. Hence, the large checkpoint files were not actually there as git-lfs takes care of downloading those. Hence, seemingly corrupt files.

@NicolasH2 you should be able to solve your issue with (something like) the following steps:

1. Removing the `stable-diffusion-v-1-4-original` repository
2. Installing git-lfs:  `conda install -c conda-forge git-lfs`
3. Running `git lfs install`
4. `git clone https://huggingface.co/CompVis/stable-diffusion-v-1-4-original`
