### ISSUE TITLE
Slower speed then original branch

### ISSUE THREAD

**Issue by PotatoHate** [CompVis/stable-diffusion#125]
Edit: using optimizedSD/optimized_txt2img.py

**Optimized branch with** `--seed 27 --n_iter 1 --n_samples 1 --ddim_steps 50`

![image](https://user-images.githubusercontent.com/10143526/187327759-2ee335c9-b69a-4b77-b552-162d2e9fdd5a.png)

**Original branch with same settings and it produces same output image but it does it 8 times faster:**

![image](https://user-images.githubusercontent.com/10143526/187327979-4572fc83-4a47-4128-8904-0d5475e483f6.png)

Running on 3090

**Comment by d12306** [comment]
@PotatoHate , do you know where is the optimizedSD/optimized_txt2img.py?
