### ISSUE TITLE
No module named 'imwatermark'

### ISSUE THREAD

**Issue by Neosettler** [CompVis/stable-diffusion#139]
Using Windows 10:

Install git
Install Miniconda3
Miniconda3 console:
conda env create -f environment.yaml
conda activate ldm

txt2img.py --prompt "robot, silver" --W 512 --H 512 --n_samples 1 --n_iter 4 --ddim_steps 50 --seed 435261183 --scale 7.5 --outdir "out" --plms

File "txt2img.py", line 8, in <module>
    from imwatermark import WatermarkEncoder
ModuleNotFoundError: No module named 'imwatermark'

same error even after : pip install imWatermark

What am I missing?

**Comment by fat-tire** [comment]
Did you try

     pip install invisible-watermark

**Comment by Neosettler** [comment]
Hi, thank you for your suggestion fat-tire. After trying the above, still getting the same result.

**Comment by HarleysZhang** [comment]
Have you solve this problem, i have same problem!

**Comment by Neosettler** [comment]
Not yet, I'm guessing the Python environment might be messed up. I don't understand what Conda is for so I'm still struggling to get SD to work.

**Comment by fat-tire** [comment]
Maybe explicitly try:

     pip install https://github.com/ShieldMnt/invisible-watermark/archive/refs/tags/0.1.5.tar.gz

See [here](https://github.com/ShieldMnt/invisible-watermark) for the whole project

That's the latest version.  (also try substituting `pip3` for `pip` jic)

**Comment by nerdyrodent** [comment]
Make sure you've got the current code. git pull again as invisible-watermark is right there in the environment file.

**Comment by davidtsong** [comment]
Where did the requirements.txt file go? haha

**Comment by nickums** [comment]
in what directory should I find imwatermark?

**Comment by saboTec** [comment]
i have all the invisible-watermark installed and yet i get the same message. is it because of the some dependencies or paths?

**Comment by Jamie725** [comment]
I tried this and it worked:
from imwatermark import WatermarkEncoder
Just use lower case w instead of W

**Comment by DeepSeek-git** [comment]
pip install invisible-watermark 
works
