### ISSUE TITLE
"ResolvePackageNotFound" - Env creation

### ISSUE THREAD

**Issue by Chii-Onan** [CompVis/stable-diffusion#145]
When attempting to create an env by running these commands;
```
conda env create -f environment.yaml
conda activate ldm
```
I get;
```
ResolvePackageNotFound: 
  - cudatoolkit=11.3
  - pytorch=1.11.0
  - pip=20.3
  - torchvision=0.12.0
  - python=3.8.5
  ```

How can I fix this?

Some additional info:
```
OS: Ubuntu 22.04.1 LTS aarch64 
Host: KVM Virtual Machine virt-4.2 
Kernel: 5.15.0-1016-oracle 
CPU: (4) 
GPU: 00:01.0 Red Hat, Inc. Virtio GPU 
Memory: 23988MiB
```

**Comment by vipsy** [comment]
I have the same issue in macOs. 
Though I get a one step ahead by doing this. 
in your environment.yaml, move those lines under pip section
you will have to change '=' to '==' there.

**Comment by Chii-Onan** [comment]
I was able to resolve this issue, so I will be closing this now.

Thank you @vipsy for helping!

**Comment by johnnytomcat** [comment]
OSX is on v9.0
https://anaconda.org/anaconda/cudatoolkit

Update the environment.yaml to 
```
  - cudatoolkit=9.0
  ```

**Comment by vipsy** [comment]
Thanks @johnnytomcat  this resolved my issue.
