### ISSUE TITLE
Running on M1 macs

### ISSUE THREAD

**Issue by parunach** [CompVis/stable-diffusion#152]
I wonder if this can work with the GPUs in Macbook Pro M1 Pro/Max.

I have cuda toolkit problem.

**Comment by nobodyCloak** [comment]
Hiya @parunach ! See #25 for all of the discussion related to getting this to run on an M1. Kind of a lot, but if you are interested in getting it to work then you should read everything posted there and follow the instructions given in that issue before asking anything else in that thread. (spoiler alert: it can work!)

**Comment by GLivshits** [comment]
You just have to replace all "cuda" calls and devices with "cpu" ones. It worked for me
