### ISSUE TITLE
ModuleNotFoundError: no module named "ldm"

### ISSUE THREAD

**Issue by Nughu** [CompVis/stable-diffusion#160]
I generated the conda environment using environment.yaml, and activated it in my docker console. When I try to run txt2img.py, I get the 

ModuleNotFoundError: no module named "ldm".

According to the tutorial I followed, this capability should have been set up by creating the conda env. What am I missing?
![IMG_20220901_190922](https://user-images.githubusercontent.com/112648460/187972641-fa74a1d8-dc74-4576-a844-8b2a400a4dfa.jpg)

**Comment by naturalethic** [comment]
While `txt2img` worked fine for me, `img2img` was presenting this error when running.  The fix is to insert this line somewhere above the ldm import:

```python
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))
```

**Comment by Nughu** [comment]
@naturalethic thank you so much, this solved it!
