### ISSUE TITLE
License Clarification

### ISSUE THREAD

**Issue by ryanrussell** [CompVis/stable-diffusion#2]
This looks like an interesting project; however, my limited understanding of your licensing appears to make the code unusable for 3rd parties.

Perhaps it's just incomplete? :)

Any chance you could clarify more around this so the community can better understand your intent and what constitutes acceptable use of the https://github.com/CompVis/stable-diffusion/ repository?

![image](https://user-images.githubusercontent.com/523300/184344202-8291bdc6-ba7f-4ae2-b7f0-5d669f053041.png)

Also, would it be possible to clarify the relationship between `CompVis/stable-diffusion` and https://github.com/pesser/stable-diffusion (MIT license)?

Best,
Ryan

**Comment by ryanrussell** [comment]
Attached is a link to common licensing templates if it helps: https://github.com/licenses/license-templates/tree/master/templates

**Comment by rromb** [comment]
This license holds for the weights (parameters of the neural network), which are currently only available for research. 
We are working on a more permissive license for the weights which we hope to release soon.
https://github.com/pesser/stable-diffusion contains developing code for https://github.com/CompVis/stable-diffusion and comes with an MIT license, but no model weights.

**Comment by ryanrussell** [comment]
@rromb Thanks for the clarification!

One question that I'm not clear on -- If a 3rd generates an image using the code and weights from `CompVis/stable-diffusion` -- would you consider those output images to be an "indirect distribution of the weights"

Basically -- Are you allowed to publish an image created with code from this repository?

It's understood that this is a young project -- please take these questions as a request for guidance; not criticism :)

Best,
Ryan

**Comment by ryanrussell** [comment]
Thanks for the awesome updates on the license @rromb !!

For readers in the future: 
- [License Details on GitHub](https://github.com/CompVis/stable-diffusion/blob/main/LICENSE)
- [License Details on HuggingFace](https://huggingface.co/spaces/CompVis/stable-diffusion-license)
- [License Blog Post on Ethics and Legal Considerations](https://stability.ai/blog/stable-diffusion-public-release)
