### ISSUE TITLE
Is it possible to use the cpu for sampling?

### ISSUE THREAD

**Issue by alienhd** [CompVis/stable-diffusion#20]
Wanted to try sampling on cpu but can't get it to work. Are there any solutions for this problem?

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cpu and cuda:0!

**Comment by jamesthesnake** [comment]
i don't think so

**Comment by leszekhanusz** [comment]
You could use `export CUDA_VISIBLE_DEVICES=""` so that cuda does not see your gpu, but you would probably have an other error.

See also [latent-diffusion PR #123](https://github.com/CompVis/latent-diffusion/pull/123)

**Comment by alienhd** [comment]
@leszekhanusz Thanks for your help but can i ask you where you put the `export CUDA_VISIBLE_DEVICES=""` argument?

**Comment by leszekhanusz** [comment]
> @leszekhanusz Thanks for your help but can i ask you where you put the `export CUDA_VISIBLE_DEVICES=""` argument?

In the bash console, before running the program, assuming you are on Linux. It is simply setting an environment variable.
