### ISSUE TITLE
stable-diffusion vs diffusers?

### ISSUE THREAD

**Issue by Neosettler** [CompVis/stable-diffusion#204]
The description might as well be in Chinese. Anyone care to explain what's the difference between stable diffusion and diffusers and maybe why to choose one over the other? 
[diffusers](https://github.com/huggingface/diffusers)

I mean, the first steps is giving us hard choices that I would like to comprehend concerning tech/models:
[CompVis](https://huggingface.co/CompVis)

thank you,

**Comment by ccimage** [comment]
我的理解  Diffusers 是用于训练AI， 面向的是视频声音等艺术创作。 然后他们的一个员工弄出来一个分支就是文本转图片，命名为stable diffusion。 然后又合并这个分支到Diffusers里

**Comment by johnowhitaker** [comment]
The `diffusers` library is a (relatively new) project from the huggingface team to try to build a general library for diffusion models. They support stable diffusion and are actively developing extra features around the core model. 
This repository (CompVis/stable-diffusion) was made by the team behind the stable diffusion model specifically and has some code to show how to use the model. 
Both can be used to generate images, but they have different design goals. If you just want a script to generate pics, you may as well use the example in this repository. If you want to do it with code, and maybe write your own pipelines with extra tricks, then maybe check out the diffusers implementation. At the moment lots of people are using both and there are fans of each approach :) Intro to using it with HF: https://huggingface.co/blog/stable_diffusion
