### ISSUE TITLE
How to download a checkpoint or model.ckpt?

### ISSUE THREAD

**Issue by 1558359609** [CompVis/stable-diffusion#210]
I have seen four weights from sd-v1-1.ckpt  to sd-v1-4.ckpt, but I dont know how to download it.

Thanks

**Comment by 1558359609** [comment]
I have solved this problem.
I can download it from huggingface. 
https://huggingface.co/CompVis/stable-diffusion-v-1-4-original

**Comment by prismspecs** [comment]
Thanks for the link! Is it intentionally hidden?
