### ISSUE TITLE
I want AI to learn nouns and images of Japanese tourist attractions as well.

### ISSUE THREAD

**Issue by miracle777** [CompVis/stable-diffusion#212]
I am not good at drawing pictures.
I am happy because I have expanded my world of expression with Stable Diffusion.
I would like to thank everyone who has developed Stable Diffusion.

I wanted to paint Goryokaku, a tourist attraction in Japan.
But I instructed Stable Diffusion with prompts, but they didn't draw it.
I thought that if I could get AI to learn about the scenery of Japanese sightseeing spots, more people would be able to make use of it.
Please consider this.

**Comment by KostyaAtarik** [comment]
You can pass the existing image of Goryokaku to img2img script and use text prompt just to stylize it to a different style.

**Comment by miracle777** [comment]
Thank you very much.
I will try it.
