### ISSUE TITLE
Unclear ReadMe on how to proceed with "After obtaining the weights, link them"

### ISSUE THREAD

**Issue by grimdeathr** [CompVis/stable-diffusion#23]
How does one obtain weights? Why arent there any links?

**Comment by MikeColes** [comment]
"The Stable Diffusion weights are currently only available to universities, academics, research institutions and independent researchers. Please request access applying to [this](https://stability.ai/academia-access-form) form"

**Comment by grimdeathr** [comment]
So how is any of this open source

**Comment by johndpope** [comment]
I suspect there will be diy models popping up in the wild (presuming we having training code)\
full terms - breakdown of existing models here
https://huggingface.co/CompVis/stable-diffusion

**Comment by Utopiah** [comment]
See https://github.com/CompVis/stable-diffusion/issues/1 , basically according to https://twitter.com/EMostaque/status/1559105822776492032 optimized weights should be available "soon" AFAICT.

**Comment by breadbrowser** [comment]
> So how is any of this open source

it's as open source dalle 2

**Comment by breadbrowser** [comment]
> I suspect there will be diy models popping up in the wild (presuming we having training code) full terms - breakdown of existing models here https://huggingface.co/CompVis/stable-diffusion
> 
> UPDATE That is not Stable Diffusion, it's an older model that has been available since April - latent diffusion. https://github.com/pesser/stable-diffusion#model-zoo
> 
> online demo https://replicate.com/pesser/stable-diffusion

that's latent diffusion

**Comment by kingofprank** [comment]
I have applied for academic grant but have not received any response. How long will it take to get a reply?

**Comment by Baughn** [comment]
> I have applied for academic grant but have not received any response. How long will it take to get a reply?

AIUI, it'll be released publicly in 4 days anyway. So at this point there's not much point... probably.

**Comment by breadbrowser** [comment]
the demo is here https://huggingface.co/spaces/stabilityai/stable-diffusion

**Comment by grimdeathr** [comment]
Anybody know if it has been released?
