### ISSUE TITLE
Multi GPU generating 

### ISSUE THREAD

**Issue by dinosaurtirex** [CompVis/stable-diffusion#241]
How to use multiple gpus?
I try to modify code, but there is an error:

` AttributeError: 'DataParallel' object has no attribute 'num_timesteps'`

Here is modification:
```
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
config = OmegaConf.load(f"{opt.config}")
model = load_model_from_config(config, f"{opt.ckpt}")
model = torch.nn.DataParallel(model, device_ids = [0, 1])
model = model.to(device)
```
instead of 
```
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
config = OmegaConf.load(f"{opt.config}")
model = load_model_from_config(config, f"{opt.ckpt}")
model = model.to(device)
```
Full error log:

```
C:\Users\kgera\.conda\envs\ldm\lib\site-packages\torch\nn\parallel\data_parallel.py:30: UserWarning:
    There is an imbalance between your GPUs. You may want to exclude GPU 1 which
    has less than 75% of the memory or cores of GPU 0. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))
Traceback (most recent call last):
  File ".\scripts\txt2img.py", line 282, in <module>
    main()
  File ".\scripts\txt2img.py", line 197, in main
    sampler = PLMSSampler(model)
  File "c:\users\kgera\desktop\stable-diffusiton\stable-diffusion\ldm\models\diffusion\plms.py", line 15, in __init__
    self.ddpm_num_timesteps = model.num_timesteps
  File "C:\Users\kgera\.conda\envs\ldm\lib\site-packages\torch\nn\modules\module.py", line 1207, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DataParallel' object has no attribute 'num_timesteps'
```
As i understand, this error occurs because model try to call some class method which was not implemented for nn.DataParallel model. So there is any option to start generating for multi gpu devices?

**Comment by Drew00785** [comment]
I've been playing with this as well, you need to update model.num_timesteps to model.module.num_timesteps You'll need to do this in a few other places as well, or at least I had to in ddim.py and txt2img.py while attempting to get txt2img.py running with dataparallel on my K80. I'm using pretty much the same thing you have here and it runs without errors but it's not utilizing both GPU's and still runs out of memory on GPU 0 if I try to take the resolution higher. I've also been using export CUDA_VISIBLE_DEVICES=0,1 and echo $CUDA_VISIBLE_DEVICES to make sure both GPU's are visible. I'm wondering if I need to make some changes in other files like attention.py or model.py or maybe I just need to tweak what I have because you seem to be much closer than I've gotten.

**Comment by dinosaurtirex** [comment]
Thank you!

> I've been playing with this as well, you need to update model.num_timesteps to model.module.num_timesteps You'll need to do this in a few other places as well, or at least I had to in ddim.py and txt2img.py while attempting to get txt2img.py running with dataparallel on my K80. I'm using pretty much the same thing you have here and it runs without errors but it's not utilizing both GPU's and still runs out of memory on GPU 0 if I try to take the resolution higher. I've also been using export CUDA_VISIBLE_DEVICES=0,1 and echo $CUDA_VISIBLE_DEVICES to make sure both GPU's are visible. I'm wondering if I need to make some changes in other files like attention.py or model.py or maybe I just need to tweak what I have because you seem to be much closer than I've gotten.

**Comment by Drew00785** [comment]
No problem. Were you able to get dataparallel working with these changes? I'm not getting errors but GPU1 stays idle using vanilla SD with a K80. I haven't been able to replicate what you're seeing "There is an imbalance between your GPUs" Do you mind letting me know if you're using a fork, what GPU you're running, or if you've made changes elsewhere to get things working. I'd really love to get this figured out. TIA

**Comment by dinosaurtirex** [comment]
> No problem. Were you able to get dataparallel working with these changes? I'm not getting errors but GPU1 stays idle using vanilla SD with a K80. I haven't been able to replicate what you're seeing "There is an imbalance between your GPUs" Do you mind letting me know if you're using a fork, what GPU you're running, or if you've made changes elsewhere to get things working. I'd really love to get this figured out. TIA
i am using this fork, it can generate 1024 x 1024 even on 2080 ti, so i dont need anymore to use two GPU's 
https://github.com/basujindal/stable-diffusion

**Comment by aliasfoxkde** [comment]
I'm using OptimizedSD version of Stable Diffusion for this reason (which doesn't crash and seems to work better, with maybe a minor performance loss), but I was considering a new system build and was just curious if dual-GPU support would be a thing. Thanks guys!

**Comment by toonpeters** [comment]
Did the same, but I have an attribute error for the Dataparallel object:
`AttributeError: 'DataParallel' object has no attribute 'ema_scope'

full error log:
`Traceback (most recent call last):
  File "scripts/txt2img.py", line 369, in <module>
    main()
  File "scripts/txt2img.py", line 308, in main
    with model.ema_scope():
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'DataParallel' object has no attribute 'ema_scope'
`

**Comment by zyc-bit** [comment]
> No problem. Were you able to get dataparallel working with these changes? I'm not getting errors but GPU1 stays idle using vanilla SD with a K80. I haven't been able to replicate what you're seeing "There is an imbalance between your GPUs" Do you mind letting me know if you're using a fork, what GPU you're running, or if you've made changes elsewhere to get things working. I'd really love to get this figured out. TIA

Hi, I also want to use multiple GPUs to generate images, have you been able to do it? @Drew00785

**Comment by CyanRenault** [comment]
> > No problem. Were you able to get dataparallel working with these changes? I'm not getting errors but GPU1 stays idle using vanilla SD with a K80. I haven't been able to replicate what you're seeing "There is an imbalance between your GPUs" Do you mind letting me know if you're using a fork, what GPU you're running, or if you've made changes elsewhere to get things working. I'd really love to get this figured out. TIA
> 
> Hi, I also want to use multiple GPUs to generate images, have you been able to do it? @Drew00785

老兄 你有解决这个问题吗

**Comment by zyc-bit** [comment]
> 
not yet...
