### ISSUE TITLE
How to generate better resolution if gpu cant handle that?

### ISSUE THREAD

**Issue by dinosaurtirex** [CompVis/stable-diffusion#242]
Is there any options to deincreased speed of generation and increased resolution? Is it even possbile? Or i just need better GPU?

**Comment by tamueller** [comment]
if you want to sacrifice speed, you can get higher resolutions with: https://github.com/basujindal/stable-diffusion

**Comment by tails101** [comment]
there is upscaler in web ui that is quite effective.

**Comment by dinosaurtirex** [comment]
> if you want to sacrifice speed, you can get higher resolutions with: https://github.com/basujindal/stable-diffusion

looks like solution. thanks
