### ISSUE TITLE
Diffusion Stalls After 50th Iteration Loop

### ISSUE THREAD

**Issue by MojoJojo43** [CompVis/stable-diffusion#259]
**SOLUTION** - It was indeed my cores heating up that was causing the stall. I tweaked my fan settings using GPU Tweak III and that did the trick!

Howdy all,

Every time I run "--n_iter", it hangs once it goes over the 50th iteration. So for example, if I add let's say "--n_iter 100" to my prompt and let it run, then somewhere along the way it ends up hanging. This morning I woke up and noticed it hung at 52/100. 

GPU is fine, never got over 90 degrees so I ruled out heat being an issue..... I think. No idea what I'm talking about over here.

Any thoughts or suggestions?

Thanks

UPDATE

I have to take back the 90 degrees comment. I looked in the log and realized I was looking at the wrong date. It did actually get up to 98 degrees...... so pretty friggin hot. I moved my system so that the exhaust is pointing out towards the middle of the room instead of towards the wall with fans redirecting the air. 

We shall see.

**Comment by Ouro17** [comment]
Is this fix for you already?

**Comment by MojoJojo43** [comment]
> Is this fix for you already?

yes, I updated this post up top. Thanks!
