### ISSUE TITLE
Error during running `python inpaint.py`

### ISSUE THREAD

**Issue by AlonzoLeeeooo** [CompVis/stable-diffusion#277]
Hi there. An unknown error occurs when I was running the command `python inpaint.py --indir image_dir/ --outdir output_dir` (`image_dir` and `output_dir` denotes input images and output repectively). The error is:
`RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 24 but got size 25 for tensor number 1 in the list.`

Would you please check if there is any problem with your source code? Thanks in advance!

**Comment by AlonzoLeeeooo** [comment]
It seems that the input images should be in size of `512`. By running the official examples the code works.

**Comment by KyriaAnnwyn** [comment]
The images should be of multiple 64 size. In all scripts other setting give such kind of error
