### ISSUE TITLE
Maximum length of textual prompt allowed for txt_to_img

### ISSUE THREAD

**Issue by shivangibithel** [CompVis/stable-diffusion#282]
Can you change the maximum length of the allowed prompt to a bigger number than 77?

**Comment by gregturk** [comment]
Changing the 77 token limit for the text embedding model would require retraining the entire CLIP model.   This takes a large amount of compute resources.  Moreover, I do not think the dataset that OpenAI assembled (which is called WebImageText) has been made public.  You can read the original article about CLIP here:  https://arxiv.org/abs/2103.00020

It is quite possible that Stability AI is training new text embedding models to be used for later versions of Stable Diffusion.   We will have to just wait and see.
