### ISSUE TITLE
I can't turn off the NSFW filter

### ISSUE THREAD

**Issue by Igglepud** [CompVis/stable-diffusion#331]
I tried looking for NSFW and the word "safety" in both dream.py and text2img.py, but nothing is there to change. Everything I make comes back as a black image. I assume it's the green box issue, but I can't disable the safety checks to tell. How do you turn this off so I can see my outputs?

**Comment by Cyberes** [comment]
Stop generating porn.

**Comment by Igglepud** [comment]
> Stop generating porn.

Ha! If only that was the issue. My last prompt was "potato in a hammock." Before that I tried "kitten butler" and "blatant patriotism". I should also note that this is using dream. If I use txt2img it works about 50%.

**Comment by 2phx** [comment]
Looking for same answer

**Comment by dlondero** [comment]
[Safety checker](https://github.com/CompVis/stable-diffusion/blob/69ae4b35e0a0f6ee1af8bb9a5d0016ccb27e36dc/scripts/txt2img.py#L309) maybe?

**Comment by Igglepud** [comment]
> [Safety checker](https://github.com/CompVis/stable-diffusion/blob/69ae4b35e0a0f6ee1af8bb9a5d0016ccb27e36dc/scripts/txt2img.py#L309) maybe?

That's my problem. My txt2img.py doesn't look like that. If I ctrl+f, the word "safety" isn't in it.

**Comment by Igglepud** [comment]
Just wasted another four hours rendering black boxes. So frustrating.

**Comment by dlondero** [comment]
Well did you pull `main` branch to get latest commits?

**Comment by Igglepud** [comment]
> Well did you pull `main` branch to get latest commits?

I used this guide: https://github.com/joelparkerhenderson/stable-diffusion-macos-install-help

Just saw it doesn't come from CompVis, it comes from here: 

git clone https://github.com/lstein/stable-diffusion.git

**Comment by Igglepud** [comment]
OK, cloned the main from here and the files look like they are supposed to. Thanks! I'll run that when I get home. Need to move a bunch of things around now.

**Comment by 2phx** [comment]
https://colab.research.google.com/drive/1nHnP9casbna4ppEuVOM07G3SbjT-ojgk?usp=sharing#scrollTo=yEErJFjlrSWS

There is a line here that does it, didn't try to update it in original repo here, but should work in theory.

def dummy(images, **kwargs): return images, False 
pipe.safety_checker = dummy

**Comment by 2phx** [comment]
https://github.com/JustinGuese/stable-diffusor-docker-text2image/blob/master/txt2img.py

On another thread, someone posted fixed txt2img.py

**Comment by Igglepud** [comment]
> https://github.com/JustinGuese/stable-diffusor-docker-text2image/blob/master/txt2img.py
> 
> On another thread, someone posted fixed txt2img.py

What's this do? Fix the import issue?

**Comment by 2phx** [comment]
> 

removes safety filter

**Comment by Igglepud** [comment]
> > 
> 
> removes safety filter

Thanks! I solved that, but now I'm stuck with the watermark.

**Comment by 2phx** [comment]
> 

Update me if you get watermark solved :)

**Comment by Igglepud** [comment]
> > 
> 
> Update me if you get watermark solved :)

I ran pip install imWatermark and changed line 8 to this:

from imWatermark import watermark

Now I'm getting one about no diffusers module.

**Comment by Igglepud** [comment]
And now it says my model file doesn't exist...

**Comment by Igglepud** [comment]
OK, running! We'll see if I get any images.

**Comment by Igglepud** [comment]
"Torch not compiled with CUDA enabled"...

**Comment by Igglepud** [comment]
Running again, this time with CUDA. Didn't know I even had a GPU in this thing.

**Comment by Igglepud** [comment]
Tediously going through .py files as they crash and changing all "cuda" references to "cpu"

**Comment by Igglepud** [comment]
> > 
> 
> Update me if you get watermark solved :)

I deleted the watermark. Maybe that's naughty, but now it runs. Getting weird memory errors, but I can fix that (I think). Going to close this since my original issue is resolved.

**Comment by RahulBhalley** [comment]
What prompt did you guys put for NSFW? I couldn't get anything dirty even after removing safety check.

**Comment by Ccode-lang** [comment]
> What prompt did you guys put for NSFW? I couldn't get anything dirty even after removing safety check.

You are not supposed to use this model for NSFW.  As said before:

> Stop generating porn.

**Comment by RahulBhalley** [comment]
Everyone has freedom to do what they want to.

**Comment by Cyberes** [comment]
> What prompt did you guys put for NSFW? I couldn't get anything dirty even after removing safety check.

"little girl"

**Comment by RahulBhalley** [comment]
> "little girl"

Umm, I'd rather write something else.

**Comment by docteurzoidberg** [comment]
seems to have trouble drawing a duck's duckbill correctly without triggering the nfsw, almost all prompt i try ends with lots of nsfw triggerers

**Comment by Avishka-Perera** [comment]
After instantiating the pipeline, just before feeding the prompts, do this
```
def disabled_safety_checker(images, clip_input):
    if len(images.shape) == 4:
        num_images = images.shape[0]
        return images, [False]*num_images
    else:
        return images, False
pipeline.safety_checker = disabled_safety_checker
```
This will turn off the NSFW checker. Make sure to disable this after doing all the configurations of the pipeline. Else it might throw errors. example:
```
# instantiate and configure the pipeline
model_id = "CompVis/stable-diffusion-v1-4"
pipe = DiffusionPipeline.from_pretrained(model_id, torch_dtype=torch.float16).to("cuda")
pipe.enable_attention_slicing() # saves GPU memory
pipe.enable_xformers_memory_efficient_attention() # speeds inferencing

# disables safety checks
def disabled_safety_checker(images, clip_input):
    if len(images.shape)==4:
        num_images = images.shape[0]
        return images, [False]*num_images
    else:
        return images, False
pipe.safety_checker = disabled_safety_checker

# generate and save images
pipe_res = pipe("An astronaut riding a horse on a desert", num_inference_steps=50, guidance_scale=7.5)
image = pipe_res.images[0]
image.save(f"results/astronaut.jpg")

```
