### ISSUE TITLE
Why does txt2img have this result. lol.

### ISSUE THREAD

**Issue by qq1846482927** [CompVis/stable-diffusion#341]
I tried to run txt2img with the command "python scripts/txt2img.py --prompt "a photograph of a eggplant swimming" --plms", and I got this result, didI found the bonus scene? lol

![微信图片_20220930233406](https://user-images.githubusercontent.com/54617673/193305861-a1ab8fb9-28c6-4887-b1d3-742711193193.jpg)

**Comment by 0asa** [comment]
Because of this: https://github.com/CompVis/stable-diffusion/blob/main/scripts/txt2img.py#L87
