### ISSUE TITLE
Error When Attempting to Increase --ddim_steps above 200.

### ISSUE THREAD

**Issue by CryptoEconomize** [CompVis/stable-diffusion#342]
I can't seem to increase the --ddim_steps above 200.  If I set it above 200 it will use result in 250 steps.  If I try to go above 250 it results in an error except using --ddim_steps 350 which then results in 500 steps.

Aside from that I can't set --ddim_steps above 200 without getting this error.  How can I resolve this to increase the number of steps set with a --ddim_steps flag in prompt?

Currently set @ --ddim_steps 550 which results in the following.

```
Traceback (most recent call last):
  File "scripts/orig_scripts/txt2img.py", line 320, in <module>
    main()
  File "scripts/orig_scripts/txt2img.py", line 270, in main
    samples_ddim, _ = sampler.sample(S=opt.ddim_steps,
  File "x:\xxx\xxx\miniconda3\envs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "x:\xxx\xxx\stable-diffusion\ldm\models\diffusion\ddim.py", line 148, in sample
    self.make_schedule(ddim_num_steps=S, ddim_eta=eta, verbose=verbose)
  File "x:\xxx\xxx\stable-diffusion\ldm\models\diffusion\ddim.py", line 87, in make_schedule
    ) = make_ddim_sampling_parameters(
  File "x:\xxx\xxx\stable-diffusion\ldm\modules\diffusionmodules\util.py", line 94, in make_ddim_sampling_parameters
    alphas = alphacums[ddim_timesteps]
IndexError: index 1000 is out of bounds for dimension 0 with size 1000
```
I also tried taking the --ddim_steps out of my prompt and changing it in the txt2img.py here as well but using anything over 250 I result the same `IndexError: index 1000 is out of bounds for dimension 0 with size 1000 `
```
parser.add_argument(
        "--ddim_steps",
        type=int,
        default=250,
        help="number of ddim sampling steps",
```
        
        1-200 ddim_steps work as normal.  
        Over 200 results in 250 ddim_steps.
        350 results in 500 ddim_steps.
        
        How to resolve?

**Comment by CryptoEconomize** [comment]
I also tried taking the --ddim_steps out of my prompt and changing it in the txt2img.py here as well but using anything over 250 I result the same `IndexError: index 1000 is out of bounds for dimension 0 with size 1000`

`    parser.add_argument(
        "--ddim_steps",
        type=int,
        default=250,
        help="number of ddim sampling steps",`
        
        1-200 ddim_steps work as normal.  
        Over 200 results in 250 ddim_steps.
        350 results in 500 ddim_steps.
        
        How to resolve?

**Comment by ryanirl** [comment]
I believe this has to do with the problem as mentioned in issue #111.

**Comment by CryptoEconomize** [comment]
> 

ty
