### ISSUE TITLE
`txt2img.py` killed upon start

### ISSUE THREAD

**Issue by h3x4g0ns** [CompVis/stable-diffusion#352]
I'm running a RTX 3090 with a Ryzen 5 3600 16gb RAM running on ARCH. Everytime I try to run `python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms` the following occurs.

```sh
Global seed set to 42
Loading model from models/ldm/stable-diffusion-v1/model.ckpt
Global Step: 470000
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
[1]    52429 killed     python scripts/txt2img.py --prompt  --plms
```

Looking at the resource monitor in linux, it's maxing out to 15.5gb RAM and then running kill. This makes no sense to me because users have reported to run models with significantly less RAM. Am I missing a key setting?

**Comment by AshtakaOOf** [comment]
Similar or same problem here.
Fedora 36 with a RTX 3070 mobile.
The text2img.py doesn't work at least [OptimizedSD](https://github.com/basujindal/stable-diffusion) does work, so you should use that while we wait for help on this issue.

**Comment by h3x4g0ns** [comment]
> Similar or same problem here.
> Fedora 36 with a RTX 3070 mobile.
> The text2img.py doesn't work at least [OptimizedSD](https://github.com/basujindal/stable-diffusion) does work, so you should use that while we wait for help on this issue.

Okay update: look like you need a minimum of 12gb RAM for the entire script. For whatever reason I had some open servers and Docker Containers running that were choking memory resources. After removing them it seems to work fine for most tests. Althought... [OptimizedSD](https://github.com/basujindal/stable-diffusion) is definitely the sure shot here. Definitely need a RAM upgrade soon though lol...

**Comment by AshtakaOOf** [comment]
Oh I see maybe that's my problem i'll see tomorrow.

**Comment by AshtakaOOf** [comment]
You can close this issue if you want @h3x4g0ns

**Comment by itsdawei** [comment]
I am having the exact same problem. 
> Looking at the resource monitor in linux, it's maxing out to 15.5gb RAM and then running kill. This makes no sense to me because users have reported to run models with significantly less RAM. Am I missing a key setting?

As far as I can tell there is no other processes running on my machine (I'm using a google cloud VM).

> For whatever reason I had some open servers and Docker Containers running that were choking memory resources. After removing them it seems to work fine for most tests.

I also resolved the issue temporarily by using [OptimizedSD](https://github.com/basujindal/stable-diffusion).

**Comment by jongdetim** [comment]
I have a similar issue, but it gets killed during model loading. I don't see any logs or a trace. It just says 'killed' & I'm left to guess if it ran out of ram, of gpu vram, or something else.. appreciate any help.

**Comment by AshtakaOOf** [comment]
That's just what happen when you run out of ram on Linux.
The minimum of ram is 16gb for actually loading models.

**Comment by jongdetim** [comment]
Couldn't find a minimum of 16gb ram anywhere in the readme or online.. guess I won't be running it through a remote env then.

**Comment by h3x4g0ns** [comment]
I think based on what I'm seeing, you need at lest 14-16gb free memory during initial loading of models. Easy fix is adding more memory, but I just closed quite a few background processes and was able to get it working. It's definitely worthwhile to add this into the documentation though.

**Comment by jongdetim** [comment]
When exactly 70% of my RAM is used, the process terminates. Somehow it's not done by Linux's OOM killer.

**Comment by AshtakaOOf** [comment]
Most Full models will use 13+ gb of ram in the initiating phase
Float32 models will use less with about 8+ gb of ram in init
Float16 models Should use less but you still won't run it on only 8 gb of ram

I recently upgraded to 32 gb of sodimm ddr4 at 3200mhz, and I can tell you that I can now load any models without crashing.
