### ISSUE TITLE
failed at installing gfpgan 

### ISSUE THREAD

**Issue by semvak12** [CompVis/stable-diffusion#387]
venv "F:\ai2\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
Commit hash: <none>
Installing gfpgan
Traceback (most recent call last):
  File "launch.py", line 168, in <module>
    prepare_enviroment()
  File "launch.py", line 124, in prepare_enviroment
    run_pip(f"install {gfpgan_package}", "gfpgan")
  File "launch.py", line 60, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "launch.py", line 32, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install gfpgan.
Command: "F:\ai2\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379 --prefer-binary
Error code: 2
stdout: <empty>
stderr:
Usage:
  F:\ai2\stable-diffusion-webui\venv\Scripts\python.exe -m pip install [options] <requirement specifier> [package-index-options] ...
  F:\ai2\stable-diffusion-webui\venv\Scripts\python.exe -m pip install [options] -r <requirements file> [package-index-options] ...
  F:\ai2\stable-diffusion-webui\venv\Scripts\python.exe -m pip install [options] [-e] <vcs project url> ...
  F:\ai2\stable-diffusion-webui\venv\Scripts\python.exe -m pip install [options] [-e] <local project path> ...
  F:\ai2\stable-diffusion-webui\venv\Scripts\python.exe -m pip install [options] <archive url/path> ...

no such option: --prefer-binary

Press any key to continue . . .

**Comment by kenncon** [comment]
Make sure you have python 3.10 installed and that git has been added to path.
I had this issue, was running python 3.7. Installed 3.10, removed the stable-diffusion-webui folder, re-cloned the repo, and reran webui-user.bat and it worked (or at least its past this issue now)

**Comment by bennett-taniguchi** [comment]
> Make sure you have python 3.10 installed and that git has been added to path. I had this issue, was running python 3.7. Installed 3.10, removed the stable-diffusion-webui folder, re-cloned the repo, and reran webui-user.bat and it worked (or at least its past this issue now)

Yeah this fixed it for me. Make sure you guys reinstall git and try adding to path (it should be in programFiles if you are on Windows). Make sure git is added to path properly if it is already 'added', errors here mean that you have issues running git commands because it isn't added to path properly.
