### ISSUE TITLE
Why downloading 1.59G file?

### ISSUE THREAD

**Issue by nmartin-sens** [CompVis/stable-diffusion#390]
I've installed Stable Diffusion on my PC, including the model, but when I start it, it seems to download a big file in the cache (see Downloading: 100% 1.59G/1.59G).

```
Loading model from mod/model-v1-4.ckpt
Global Step: 470000
UNet: Running in eps-prediction mode
CondStage: Running in eps-prediction mode
Downloading: "https://github.com/DagnyT/hardnet/raw/master/pretrained/train_liberty_with_aug/checkpoint_liberty_with_aug.pth" to /root/.cache/torch/hub/checkpoints/checkpoint_liberty_with_aug.pth
100% 5.10M/5.10M [00:02<00:00, 2.64MB/s]
Downloading: 100% 939k/939k [00:00<00:00, 1.09MB/s] 
Downloading: 100% 512k/512k [00:00<00:00, 760kB/s] 
Downloading: 100% 389/389 [00:00<00:00, 510kB/s]
Downloading: 100% 905/905 [00:00<00:00, 999kB/s]
Downloading: 100% 4.41k/4.41k [00:00<00:00, 4.47MB/s]
Downloading: 100% 1.59G/1.59G [09:00<00:00, 3.17MB/s]6100Z G [08:40<00:15, 3.38MB/s]
```

How can I prevent this to happen?

I'm using the function in a Docker image and I don't want to download this 1.59G file at each run.

See also: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/1547

**Comment by nmartin-sens** [comment]
In fact, it is a model cache file from Hugging Face that need to be copied locally + set the env variable to this folder.

**Comment by blue2517** [comment]
Hello, I use the free server to build the SD. Since the provider will clear the files outside the working folder, I have to download 1.59G again every time. This is really too slow. Can you tell me how you did it?

**Comment by nmartin-sens** [comment]
Yes, here you have the solution: https://stackoverflow.com/questions/74088262/build-docker-image-using-hugging-faces-cache

**Comment by blue2517** [comment]
> 
Thanks, it works.

**Comment by liangbingzhao** [comment]
do you know what this 1.59G file is? I use remote server to construct sd, and the network is too slow. I hope to figure out what this file is and download by myself.
