### ISSUE TITLE
OSError: Error no file named model_index.json found in directory

### ISSUE THREAD

**Issue by DjTecmo** [CompVis/stable-diffusion#394]
WHY WHY WHY WHY WHY AND WHY IS THIS ERROR HAPENING WITHOUT ANY EXPLANATION ON THE INSTRUCTIONS OF HOW TO VOID IT!!
OSError: Error no file named model_index.json found in directory /content/drive/MyDrive/stable_diffusion_weights/...

**Comment by DjTecmo** [comment]
My desperation is evident!!

**Comment by batrlatom** [comment]
using ```accelerate config``` helped me to avoid this problem

**Comment by DjTecmo** [comment]
hmm, okey i will try, Can you tell me in which cell can I find it? A day with the problem and with so much code and code I sometimes skip where it could be

**Comment by Ad4m69** [comment]
how to use it?

> using `accelerate config` helped me to avoid this problem

**Comment by DjTecmo** [comment]
> using `accelerate config` helped me to avoid this problem

You didn't describe so much, i saw this in a cell : "accelerate launch train_dreambooth.py \ " and obviously i launched it in order, i don't know what the hell more to do, you are not explaining enought, please help!

**Comment by DjTecmo** [comment]
> 

Just help me HOW? how to use it, there's a warning i saw: To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`
And i don't get where do i have to do it or which cell i did something wrong

**Comment by chen-qj** [comment]
I meet the problem when downloading the weight from Hugging Face following the readme.
```python
pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", use_auth_token=True)
```
This is the huggingface page of their model [stable-diffusion-v1-4](https://huggingface.co/CompVis/stable-diffusion-v1-4/tree/main). You need to login and agree the terms to access the repo, otherwise a 404 or 403 error. There will be the `model_index.json` and other files you need. Besides, if you set `use_auth_token=True` in the code, you need to generate a token following the guide of huggingface.

**Comment by DjTecmo** [comment]
Thank you, you really helped know more about it. About the authentication token, do i need to generate a new one? it seems like google saved the last and put it automatically and the cell checked on green as correct so i thought that was fine, thank you!

**Comment by andrruta** [comment]
> Thank you, you really helped know more about it. About the authentication token, do i need to generate a new one? it seems like google saved the last and put it automatically and the cell checked on green as correct so i thought that was fine, thank you!

I have the same problem. How did you decide that? Help me, friend!

**Comment by DjTecmo** [comment]
okey , i used to let the token_auth cell empty. It worked after filling it . but don't trust this anymore, i still got this error after some time trying to train other persons posterior time .using the notebook again to train another person, the error came out of nothing and yes, an empty file is missing when you look stablediffusion_weights, on you Drive. Idontknoe why

**Comment by DjTecmo** [comment]
> an empty file is missing when you look stablediffusion_weights, on you Drive. Idontknoe why

Bro why you only left that reply without an explanation, i don't understand this about that!!  how you make that without messing it!??

**Comment by DjTecmo** [comment]
> using `accelerate config` helped me to avoid this problem

Bro why you only left that reply without an explanation, i don't understand this about that!! how you make that without messing it!??

**Comment by DjTecmo** [comment]
> I meet the problem when downloading the weight from Hugging Face following the readme.
> 
> ```python
> pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", use_auth_token=True)
> ```
> 
> This is the huggingface page of their model [stable-diffusion-v1-4](https://huggingface.co/CompVis/stable-diffusion-v1-4/tree/main). You need to login and agree the terms to access the repo, otherwise a 404 or 403 error. There will be the `model_index.json` and other files you need. Besides, if you set `use_auth_token=True` in the code, you need to generate a token following the guide of huggingface.

Thanks but, is this issue ... emm, wait, this things are supposed to be generated on the colab and saved on my Drive directory "weights" , are you telling me something i don't know will give me what i want , how i know the json files im looking will be usefull , are not this files unique? im training on Dreambooth google colab and I just run aparently correct the cells one by one making what is need to do on each one and this error don't says me what to do or don't to let the files be generated and saved correctly to be used by Inference Cell, on the same

**Comment by andrruta** [comment]
Earlier (about two weeks ago) I worked in this colab without any problems. This problem arose after changes in the construction of the collab. Now I tried everything I can (token replacement too) but all in vain. I understand that there is no solution to the problem. I didn't find a solution on the web either unfortunately.

**Comment by DjTecmo** [comment]
exactly as you said, tried everything, but yes, thank you, we will wait for
an experts opinion so

**Comment by DjTecmo** [comment]
> Earlier (about two weeks ago) I worked in this colab without any problems. This problem arose after changes in the construction of the collab. Now I tried everything I can (token replacement too) but all in vain. I understand that there is no solution to the problem. I didn't find a solution on the web either unfortunately.

Earlier (about two weeks ago) I worked in this colab without any problems. This problem arose after changes in the construction of the collab. Now I tried everything I can (token replacement too) but all in vain. I understand that there is no solution to the problem. I didn't find a solution on the web either unfortunately.

**Comment by DjTecmo** [comment]
> Earlier (about two weeks ago) I worked in this colab without any problems. This problem arose after changes in the construction of the collab. Now I tried everything I can (token replacement too) but all in vain. I understand that there is no solution to the problem. I didn't find a solution on the web either unfortunately.

I found that having even more space than the minimum available required for the files is solving the problem. After having a trained model saved correctly in my drive(a sucessfull training with the collab) i cannot make it again with the previous one saved. because my space was just the required and sometimes less, so i solved it that way but mmm, i cannot erase more things in my drive than the important stuff so hope you all find another way or find this usefull

**Comment by danielajisafe** [comment]
The model and all files related to it, including ```model_index.json``` are downloaded to your home cache directory by default e.g ```home/username/.cache```. You should find it in something like ```home/username/.cache/models--CompVis--stable-diffusion-v1-4/snapshots/133a221b8aa7292a167afc5127cb63fb5005638b/model_index.json```. 

If you can't locate your home cache directory, you can define a specific directory where you want model and its files to be saved by doing,
```
import os
cache_dir = "path/to/my/specific/directory"
os.environ['XDG_CACHE_HOME'] = cache_dir
```

Don't forget to pass this directory in the pipeline, and I am assuming your terminal has access to internet (which was the problem in my case), by doing
```
ldm = StableDiffusionPipeline.from_pretrained(type="CompVis/stable-diffusion-v1-4", use_auth_token=MY_TOKEN,  cache_dir=cache_dir)
```
update ```MY_TOKEN``` with the token from your hugging face profile,  or you simply pass an empty string ```""```

**Comment by DjTecmo** [comment]
How do I know that this will solve my error and not generate others?

**Comment by ProtegosLeviosa** [comment]
Hi! I was wondering did you find out the solution of your first question? My problem is CompVis/stable-diffusion-v1-4 does not appear to have a file named model_index.json. I'm confused about I can’t even find where this directory is

**Comment by seraj-ghasemi** [comment]
I've find the model_index.json at https://huggingface.co/stabilityai/stable-diffusion-3-medium-diffusers/tree/main
