### ISSUE TITLE
KeyError: 'sample'

### ISSUE THREAD

**Issue by berkay3500** [CompVis/stable-diffusion#402]
My code was working just the other day, but now it is giving a key error, the pipeline is like this. Where do you think is the mistake?

device = "cuda"
pipe = StableDiffusionInpaintPipeline.from_pretrained(
    "CompVis/stable-diffusion-v1-4",
    use_auth_token=True
).to(device)

with autocast("cuda"):

images = pipe(prompt = "a wall painted red", 
                init_image=init_image, 
                mask_image=mask, 
                strength = 0.9
                # batch_size = 2, 
                # num_inference_steps = 50
                )["sample"]

**Comment by lizefield** [comment]
I faced same problem too, but check sample of this link.
https://huggingface.co/CompVis/stable-diffusion-v1-4

---

failed(previous description):

```
pipe(prompt)["sample"]
```

success:

```
pipe(prompt).images
```

**Comment by berkay3500** [comment]
Thanks!

**Comment by jackson-sandland** [comment]
This worked!

**Comment by RohanDev-ctrl** [comment]
> I faced same problem too, but check sample of this link. https://huggingface.co/CompVis/stable-diffusion-v1-4
> 
> failed(previous description):
> 
> ```
> pipe(prompt)["sample"]
> ```
> 
> success:
> 
> ```
> pipe(prompt).images
> ```

Thanks it WORKEDDD!!!!!
