### ISSUE TITLE
config for training

### ISSUE THREAD

**Issue by ssusie** [CompVis/stable-diffusion#423]
Can someone point me to a working config for training and how to run it properly?

There is no config to train the stable diffusion model. I experimented with other latent diffusion configs and tried to run  training
``` 
 python3 main.py --train --base configs/latent-diffusion/lsun_bedrooms-ldm-vq-4.yaml
```
but got the error like https://github.com/CompVis/stable-diffusion/issues/416#issue-1419696247.

I tried other configs as well but none of them seems to be working. 

When I tried 
```
python3 main.py --train --base configs/latent-diffusion/lsun_churches-ldm-kl-8.yaml
```
I get error `FileNotFoundError: [Errno 2] No such file or directory: 'models/first_stage_models/kl-f8/config.ckpt'`. Where do I get the ckpt file for that model?

Please help.
Thanks.

**Comment by ssusie** [comment]
I found the scripts how to get models/ckpt files under `scripts/download_first_stages.sh` to get the ckpt files.

**Comment by xuzekai1997** [comment]
hello, do you train the model successfully? I loaded these config and ckpt files.But when using my own dataset,it always didn't work.If you sloved this problem, could you give me some advice?Thanks a lot.

**Comment by ssusie** [comment]
Hi @xuzekai1997 , yes, I trained successfully but not on custom dataset. I used Imagenette with cin-ldm-vq-f8-ss.yaml config. Have you tested the model before running on custom dataset? II would suggest to give it a try. And one good source I used for running this is model https://youtu.be/f6PtJKdey8E
