### ISSUE TITLE
Has anyone succeeded in training from scratch?

### ISSUE THREAD

**Issue by caffeinism** [CompVis/stable-diffusion#452]
I've been trying to reproduce the Imagenet model (FID:3.6) shown in the paper for the past few days. But I ran into some problems while looking through the code.

1. Is Classifier-Free Guidance work in training process?

Implementations of DDIM and PLMS have implementations for CFG. However, in the training process, the process of entering null (idx 1000 in the case of imagenet) with a probability of p_uncond does not seem to exist in the code.

2. The autoencoder learning config is not clear.

In particular, some models in the paper are trained through VQ. But the learning codes are not integrated. I extracted the weight of imagenet-vq-4 by referring to the colab script and modified the cin-v2 specification slightly to proceed with learning. But this also doesn't work.

I'm curious at this point. Has anyone succeeded in training from Scratch? Any tips for training?

**Comment by caffeinism** [comment]
https://github.com/CompVis/latent-diffusion script has some problems. Also, the config doesn't seem to be managed correctly. The paper has been updated once, but there are problems such as inconsistency between the appendix and the main body.

LDM paper and results are very attractive, but I think the code is focused on inference. Besides, it looks like this repository has already stopped updating.

**Comment by prismformore** [comment]
@caffeinism Hi, did you successfully find the training script? Thank you.

**Comment by caffeinism** [comment]
> @caffeinism Hi, did you successfully find the training script? Thank you.

Use an appropriate LR. The LR of the default executable script is not appropriate. Specifically use --scale_lr=False.

It looks like you'll need to tweak your code a bit to use classifier-free guidance. See the latest commit at https://github.com/caffeinism/latent-diffusion. (The latent-diffusion repository is slightly different from the stable-diffusion repository, but mostly the same stuff). When I learned this, the output is actually reasonable, but I'm not sure if I can get the FID of the actual paper.
