### ISSUE TITLE
ldm module throwing Python 2 print issue

### ISSUE THREAD

**Issue by GLKSA** [CompVis/stable-diffusion#480]
Cloned stable-diffusion into VS 2019 Community edition. Installed a virtual Python environment and manually loaded the dependencies using pip and conda.  (BTW VS2019  does not recognize environment.yaml and looks for environment.yml)

When I run txt2img.py I get the well-known "print" error from the Python2 => Python3 source code upgrade.

>>> import argparse, os, sys, glob
>>> import cv2
>>> import torch
>>> import numpy as np
>>> from omegaconf import OmegaConf
>>> from PIL import Image
>>> from tqdm import tqdm, trange
>>> from imwatermark import WatermarkEncoder
>>> from itertools import islice
>>> from einops import rearrange
>>> from torchvision.utils import make_grid
>>> import time
>>> from pytorch_lightning import seed_everything
>>> from torch import autocast
>>> from contextlib import contextmanager, nullcontext
>>> from ldm.util import instantiate_from_config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\glksp\.conda\envs\ldm2\lib\site-packages\ldm.py", line 20
    print self.face_rec_model_path0
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.face_rec_model_path)?

Any help is appreciated. I realise there are no command line arguments when running this way, I assume txt2img.py uses the embedded defaults when running without args? Maybe no-one has run this module without args since before the upgrade?

**Comment by davidetalon** [comment]
I encountered the same problem. Have you installed ldm from pip?
If yes it is not the package you are looking for, the code referes to ldm module within stable diffusion

Hope it helps

**Comment by GLKSA** [comment]
Thanks,  I will delete and reload ldm. Thanks for letting me know that I am not the first with this problem.

**Comment by TnnsBeast** [comment]
> Thanks, I will delete and reload ldm. Thanks for letting me know that I am not the first with this problem.

Did you manage to get it working with reloading ldm?
