### ISSUE TITLE
Syntax issues with ldm.py

### ISSUE THREAD

**Issue by FaberDax** [CompVis/stable-diffusion#488]
Traceback (most recent call last):
  File "scripts/txt2img.py", line 17, in <module>
    from ldm.util import instantiate_from_config
  File "C:\Users\PC_NAME\anaconda3\envs\ldm\lib\site-packages\ldm.py", line 20
    print self.face_rec_model_path
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.face_rec_model_path)?

AND

Traceback (most recent call last):
  File "scripts\txt2img.py", line 17, in <module>
    from ldm.util import instantiate_from_config
  File "C:\Users\PC_NAME\anaconda3\envs\ldm\lib\site-packages\ldm.py", line 77
    print os.path.exists("%s.bz2"%(predictor_path))
          ^
SyntaxError: invalid syntax

The first error occurred and I made a cheap and nasty quick by just adding the ( ) set as it pointed out. I thought I should share this issue after seeing another error expose itself. I figured it would keep going. I must have messed up something.

**Comment by GLKSA** [comment]
OK, you have the wrong ldm. (
  delete the ldm library (pip or conda) and then run again. it will find the ldm folder which is the correct version (Python 3 version)

**Comment by FaberDax** [comment]
> OK, you have the wrong ldm. ( delete the ldm library (pip or conda) and then run again. it will find the ldm folder which is the correct version (Python 3 version)

When I do the redo environment, it gets an error of git being an unknown command but I think git is in the anaconda library.

**Comment by FaberDax** [comment]
Issue resolved. Thanks for your help @GLKSA

**Comment by jameshennessytempus** [comment]
Can close this?

**Comment by austinschrader** [comment]
Deleting the LDM package via pip and rerunning the code block does not solve this issue. 

Are part of the instructions missing, or something?

**Comment by shemca** [comment]
Am also getting this same error. Pretty sure am using the latest LDM package, have uninstalled and re-install. Same print syntax error.

**Comment by oyesterday** [comment]
I am also getting the same error. Also certain I have the latest packages, tried uninstalling and re-installing. Tried to edit the relevant lines in ldm.py but get dumped out of every system when I try to open the file.

**Comment by drusepth** [comment]
Getting this error with a fresh `pip3 install ldm`. Uninstalling and re-installing results in the same error.

```sh
$ python3 txt2img.py --prompt "prompt" --H 512 --W 512 --seed 27 --n_iter 2 --ddim_steps 50
Traceback (most recent call last):
  File "/home/ubuntu/basil/txt2img.py", line 17, in <module>
    from ldm.util import instantiate_from_config
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ldm.py", line 20
    print self.face_rec_model_path 
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```

```sh
$ python3 --version
Python 3.10.6
$ pip3 freeze | grep ldm
ldm==0.1.3
```

Viewing the ldm source code for that release ([the latest release](https://pypi.org/project/ldm/)) shows python2-style print statements. The correct "fix" for this issue seems to be to uninstall `ldm` and install it from the included `ldm` folder in this repo. Not sure what the fix would be if you're using a wrapper like `stable-diffusion-webui` which doesn't package an `ldm` folder.

**Comment by TnnsBeast** [comment]
> Getting this error with a fresh `pip3 install ldm`. Uninstalling and re-installing results in the same error.
> 
> ```shell
> $ python3 txt2img.py --prompt "prompt" --H 512 --W 512 --seed 27 --n_iter 2 --ddim_steps 50
> Traceback (most recent call last):
>   File "/home/ubuntu/basil/txt2img.py", line 17, in <module>
>     from ldm.util import instantiate_from_config
>   File "/home/ubuntu/.local/lib/python3.10/site-packages/ldm.py", line 20
>     print self.face_rec_model_path 
>     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
> ```
> 
>  ```shell
> $ python3 --version
> Python 3.10.6
> $ pip3 freeze | grep ldm
> ldm==0.1.3
> ```
> 
> Viewing the ldm source code for that release ([the latest release](https://pypi.org/project/ldm/)) shows python2-style print statements. The correct "fix" for this issue seems to be to uninstall `ldm` and install it from the included `ldm` folder in this repo. Not sure what the fix would be if you're using a wrapper like `stable-diffusion-webui` which doesn't package an `ldm` folder.

How would I install it from the included ldm folder in the repo?

**Comment by ashutosh-devel** [comment]
This was bit of a hack, but copying the ldm directory directly to 'site-packages' worked for me. I was not able to install it using any other way.

**Comment by TheBlackHacker** [comment]
Stable-diffusion doesn't really want python's ldm library, what it really wants is laten-diffusion
Just uninstall the ldm library
```
pip uninstall ldm
```

And clone stable-diffusion, then install all it's requirements
```
git clone https://github.com/CompVis/stable-diffusion
cd stable-diffusion
pip install -e .
```

**Comment by yaashwardhan** [comment]
Update the latent diffusion environment (ldm) present using:

cd Dreambooth-Stable-Diffusion-main 
conda install pytorch torchvision -c pytorch
pip install transformers==4.19.2 diffusers invisible-watermark
pip install -e .

**Comment by Kevinorve** [comment]
Well, the ldm that you installed via pip is not the ldm that program needs. They are two different things, we should get it from https://github.com/CompVis/latent-diffusion.git.
