### ISSUE TITLE
Please help me solve this

### ISSUE THREAD

**Issue by dazhijiong** [CompVis/stable-diffusion#51]
When I run the txt2img script following the readme, I find this error:
libssl.so.3: cannot open shared object file: No such file or directory
What should I do to solve this?

**Comment by CapPow** [comment]
Looks like you're environment is missing some OpenSSL shared libraries. If you're using Linux I'd check your package manager for an OpenSSL update. Also worth trying a quick stackoverflow query including your OS and the error. Finally, just in case you're new to this stuff: at least read through responses to proposed solutions before just pasting them into your command prompt.

**Comment by Zondakage** [comment]
@CapPow I am very new to this. I am simply trying to get it running locally on my computer. I could use a lot of help.
