### ISSUE TITLE
Always generating corrupted images

### ISSUE THREAD

**Issue by madeyellow** [CompVis/stable-diffusion#514]
Running stable diffusion **webui-user** with those arguments:

```
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --opt-split-attention --precision full --no-half --medvram --skip-torch-cuda-test

call webui.bat
```

Got this output (seems okay):

```
C:\StableDiffusion\stable-diffusion-webui\venv\lib\site-packages\torch\cuda\__init__.py:83: UserWarning: CUDA initialization: CUDA driver initialization failed, you might not have a CUDA gpu. (Triggered internally at  ..\c10\cuda\CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Warning: caught exception 'CUDA driver initialization failed, you might not have a CUDA gpu.', memory monitor disabled
No module 'xformers'. Proceeding without it.
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights [7460a6fa] from C:\StableDiffusion\stable-diffusion-webui\models\Stable-diffusion\sd-v1-4.ckpt
Applying cross attention optimization (InvokeAI).
Model loaded.
Loaded a total of 0 textual inversion embeddings.
Embeddings:
Running on local URL:  http://127.0.0.1:7860
```

But when image gets generated with any settings am always getting corrupted images like this:

![00000-3401729651-stylized magic character similar to ori](https://user-images.githubusercontent.com/10926877/204786401-de040469-424b-4aa5-abb1-c3ae2f8b6caa.png)
![00001-792227701-character from ori](https://user-images.githubusercontent.com/10926877/204786407-e73cad67-cd2f-4ab6-8e4d-fafd1b3a0725.png)
![00002-2758044730-character ori](https://user-images.githubusercontent.com/10926877/204786411-bad7ed2b-53b8-4fb3-830a-f312ef910dff.png)

Tried:

- Remove "--precision full --no-half" from argument = image won't generate at all;
- Remove "--opt-split-attention" = webui-user not launching

Does anyone knows how to fix it?

P.S. Am super new to stable diffusion, sorry if asking dumb or obvious questions.

**Comment by SoftwareSchlosser** [comment]
Same here with fresh install using the txt2img.py script.

**Comment by pavlexander** [comment]
I was getting corrupted images while I used 256 size. After changing to 512 it worked at least once :)
768 does not work due to vmem limit
