### ISSUE TITLE
save_onnx.py RuntimeError

### ISSUE THREAD

**Issue by GREG114** [CompVis/stable-diffusion#520]
Big hello!

I was tried to install stable-diffusion for AMD GPU for win11

there is a problem I have never solved when I running save_onnx.py
seems like its created a folder named "onnx", but nothing file created,  I have log in huggingface already

C:\Data\amd5\diffusers\venv\lib\site-packages\diffusers\models\resnet.py:122: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if hidden_states.shape[0] >= 64:
Traceback (most recent call last):
  File "C:\Data\amd5\diffusers\examples\inference\save_onnx.py", line 66, in <module>
    convert_to_onnx(pipe.unet, pipe.vae.post_quant_conv, pipe.vae.decoder, text_encoder, height=512, width=512)
  File "C:\Data\amd5\diffusers\examples\inference\save_onnx.py", line 41, in convert_to_onnx
    traced_model = torch.jit.trace(unet, check_inputs[0], check_inputs=[check_inputs[1]], strict=True)
  File "C:\Data\amd5\diffusers\venv\lib\site-packages\torch\jit\_trace.py", line 759, in trace
    return trace_module(
  File "C:\Data\amd5\diffusers\venv\lib\site-packages\torch\jit\_trace.py", line 976, in trace_module
    module._c._create_method_from_trace(
RuntimeError: Encountering a dict at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.

**Comment by PyrateGFXProductions** [comment]
I have the same error. What is the fix?
