### ISSUE TITLE
Unable to Install Stable Diffusion

### ISSUE THREAD

**Issue by Slezidav** [CompVis/stable-diffusion#538]
Please Help,  I'm having issues installing Stable Diffusion. According to my understanding I should get a URL link that takes me to stable diffusion, however it doesn't show up. It gives several error messages, what should I do?
Thanks

Already up to date.
venv "C:\Users\User\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
Commit hash: 685f9631b56ff8bd43bce24ff5ce0f9a0e9af490
Installing torch and torchvision
Traceback (most recent call last):
  File "C:\Users\User\stable-diffusion-webui\launch.py", line 294, in <module>
    prepare_environment()
  File "C:\Users\User\stable-diffusion-webui\launch.py", line 206, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch")
  File "C:\Users\User\stable-diffusion-webui\launch.py", line 49, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install torch.
Command: "C:\Users\User\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 --extra-index-url https://download.pytorch.org/whl/cu113
Error code: 1
stdout: Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu113

stderr: ERROR: Could not find a version that satisfies the requirement torch==1.12.1+cu113 (from versions: none)
ERROR: No matching distribution found for torch==1.12.1+cu113

Press any key to continue . . .

**Comment by picarojoke** [comment]
I downgraded python to 3.10.6 but the error doesn't disappear. Can someone tell me what else I need to do?

**Comment by liangbingzhao** [comment]
you need to match the version of pytorch and cuda.
