### ISSUE TITLE
Can someone help me? I'm trying to install stable diffusion but I keep getting errors. I'm very new to this kind of thing. The folder i have these in is parodies, just a general folder i created for everything.

### ISSUE THREAD

**Issue by Otaruval** [CompVis/stable-diffusion#556]
venv "G:\parodies\Github\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: <none>
Installing gfpgan
Traceback (most recent call last):
  File "G:\parodies\Github\stable-diffusion-webui\launch.py", line 294, in <module>
    prepare_environment()
  File "G:\parodies\Github\stable-diffusion-webui\launch.py", line 212, in prepare_environment
    run_pip(f"install {gfpgan_package}", "gfpgan")
  File "G:\parodies\Github\stable-diffusion-webui\launch.py", line 78, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "G:\parodies\Github\stable-diffusion-webui\launch.py", line 49, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install gfpgan.
Command: "G:\parodies\Github\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379 --prefer-binary
Error code: 1
stdout: Collecting git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379
  Cloning https://github.com/TencentARC/GFPGAN.git (to revision 8d2447a2d918f8eba5a4a01463fd48e45126a379) to c:\users\fernando\appdata\local\temp\pip-req-build-evida8eq

stderr:   Running command git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git 'C:\Users\fernando\AppData\Local\Temp\pip-req-build-evida8eq'
  fatal: unable to access 'https://github.com/TencentARC/GFPGAN.git/': error setting certificate verify locations:  CAfile: G:/parodies/Github/mingw64/ssl/certs/ca-bundle.crt CApath: none
  error: subprocess-exited-with-error

  git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git 'C:\Users\fernando\AppData\Local\Temp\pip-req-build-evida8eq' did not run successfully.
  exit code: 128

  See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

git clone --filter=blob:none --quiet https://github.com/TencentARC/GFPGAN.git 'C:\Users\fernando\AppData\Local\Temp\pip-req-build-evida8eq' did not run successfully.
exit code: 128

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Press any key to continue

**Comment by Otaruval** [comment]
I have git installed and the right Python installed and added to path

**Comment by bigwhitechen** [comment]
> I have git installed and the right Python installed and added to path

did you find a solution? I also encounter this problem

**Comment by jenuk** [comment]
From the error-message I am assuming your question is about the [stable diffusion webui by AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui). Please be aware this is a third-party tool and we cannot provide any support for it. You may want to look into the [issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue) there, both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.
