### ISSUE TITLE
module has no attribute 'FrozenCLIPEmbedder'

### ISSUE THREAD

**Issue by SPotaufeux** [CompVis/stable-diffusion#59]
Hello, thanks for the repo and I apologize in advance if it's a noob question, but when I run _python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms_ the code seems to run fine, the model is loaded, etc, then I get : 
_Traceback (most recent call last):_
[...]
_AttributeError: module 'ldm.modules.encoders.modules' has no attribute 'FrozenCLIPEmbedder'_

Does anybody know how to solve it ?
(I'm on Windows and I'm working with the latest release of Stable Diffusion, with the model sd-v1-4.ckpt, if it might help)

Thanks in advance

SPotaufeux

**Comment by taoisu** [comment]
Install the repo locally by running `pip install -e .` under the root directory. Then python will be able to locate the dependency.

**Comment by SPotaufeux** [comment]
Oh yeah thanks

**Comment by KleinXin** [comment]
> Install the repo locally by running `pip install -e .` under the root directory. Then python will be able to locate the dependency.

@SPotaufeux @taoisu 

I tried to run pip install -e . under the root directory of stable-diffusion, clip and taming-transformers. 
The problem still remains.
Could you please tell more details about how to solve it？
thx

**Comment by cyberrebe** [comment]
Hi, thank you in advance for your help, 
I tried but "Install the repo locally by running pip install -e . under the root directory." didn't work.
After: python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms
I had 
"""Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Traceback (most recent call last):
....
AttributeError: module 'ldm.modules.encoders.modules' has no attribute 'FrozenCLIPEmbedder'"""

It's really frustrating but it seems like it no other helpful info google except this tread.

**Comment by hananbeer** [comment]
it happened to me with **stable diffusion 2** model. it has resolved once I switched to another model and restarted.
quite strange as I used it before, but I think the UI does git pull every startup so perhaps something broke.

(edit: I was referring to automatic1111, so actually I'm not sure what broke it)

**Comment by zsh2000** [comment]
For me, it is because some inconsistency of several code versions. For some versions, the class is called FrozenCLIPEmbedder, with "models" having default value "ViT-L/14". For others, it is called FrozenClipEmbedder, with no default value for "model".
