### ISSUE TITLE
img2img,

### ISSUE THREAD

**Issue by liwei0826** [CompVis/stable-diffusion#60]
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 16 but got size 15 for tensor number 1 in the list.

**Comment by liwei0826** [comment]
python scripts/img2img.py --prompt "A fantasy landscape, trending on artstation" --init-img <path-to-img.jpg> --strength 0.8
![image](https://user-images.githubusercontent.com/48194881/186095191-805f1145-e191-456b-ab63-30fcb27ce44a.png)
![image](https://user-images.githubusercontent.com/48194881/186095325-5c4701b4-69bd-434c-bbef-5b6a2deacfde.png)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 22 but got size 21 for tensor number 1 in the list.

**Comment by liuyang8643** [comment]
same error...

**Comment by karray** [comment]
Does `img2img` use the same `sd-v1` weights or it is a different model and, hence, different weights? At least, the output is different (text vs img+text)

**Comment by Rehvaro** [comment]
I had this error and making it 512x512 square fixed it.
Not sure if its the resolution or only the square ratio that fixed it.

**Comment by liuyang8643** [comment]
> 

correct! resize img to 512,512 in the load_img function

**Comment by liwei0826** [comment]
> > 
> 
> 正确的！在 load_img 函数中将 img 的大小调整为 512,512

[thanks](javascript:;)

**Comment by michaelhodel** [comment]
if you want to have different resolutions / aspect ratios, just make sure to that both the height and width are multiples of 64. At least, this works for me.

**Comment by leandro-gracia-gil** [comment]
This is just a consequence of the U-net architecture. When trying to concatenate results for a level, the spatial dimensions of some x are not matching the ones from upsample(process(downsample(x))).

This should be a simple fix to support any image sizes. Just go [here](https://github.com/CompVis/stable-diffusion/blob/main/ldm/modules/diffusionmodules/openaimodel.py#L735) and replace this:
```python
       for module in self.output_blocks:
            h = th.cat([h, hs.pop()], dim=1)
            h = module(h, emb, context)
````

With this:
```python
        for module in self.output_blocks:
            if h.shape[-2:] != hs[-1].shape[-2:]:
                h = F.interpolate(h, hs[-1].shape[-2:], mode="nearest")
            h = th.cat([h, hs.pop()], dim=1)
            h = module(h, emb, context)
```

That should adjust sizes after upscaling when needed so that concatenation works. By the way, this problem also affects txt2txt when explicitly setting sizes.

**Comment by jayhxmo** [comment]
@shikhar2402 Is the following change correct?
From
`w, h = map(lambda x: x - x % 32, (w, h))`
to
`w, h = map(lambda x: x - x % 64, (w, h))`

**Comment by jayhxmo** [comment]
I'm still getting the error:
```
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same
```

**Comment by shikhar2402** [comment]
> I'm still getting the error:
> 
> ```
> RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same
> ```

@jayhxmo which weight you are using? I am using sd-v1-3.ckpt.

**Comment by Explosion-Scratch** [comment]
> I had this error and making the input image 512x512 square fixed it. Not sure if it's the resolution or only the square ratio that fixed it.

Making sure that both input and output have the **same** resolution fixed it for me =)

**Comment by g-jing** [comment]
Do you know how to change the output image size for `img2img.sh`? Thanks.

**Comment by Blinix** [comment]
> if you want to have different resolutions / aspect ratios, just make sure to that both the height and width are multiples of 64. At least, this works for me.

Tried this, works like a charm.
