### ISSUE TITLE
Unbelievably hard time getting stable diffusion running on my Mac book through terminal. ANY HELP PLEASE!

### ISSUE THREAD

**Issue by ramzillious** [CompVis/stable-diffusion#602]
I have never touched the terminal in my life besides using it to force quit apps. I have been following this https://www.youtube.com/watch?v=Jh-clc4jEvk tutorial to start running automatic1111 on my macbook and have had problems all along the way. I know that after it runs all the installations a web link should pop up where you can then hop in and start playing with stable diffusion but I havent been able to get there. All of the installations have worked properly from what Im reading in the code (alot of installations) and I just have no clue where to go next. Im extremely overwhelmed and confused but Ive been trouble shooting this for 3 days and Im not stopping now haha.

Here are a few screenshots of the errors if anyone with more knowledge than me wants to help:

<img width="789" alt="Screenshot 2023-02-04 at 7 39 16 AM" src="https://user-images.githubusercontent.com/122573313/216776932-e5de198b-79f6-44bb-885f-a3303e324f84.png">

I see it says it couldn't install a few things including web UI then goes on to continue hundreds of lines of installs...

<img width="784" alt="Screenshot 2023-02-04 at 7 34 23 AM" src="https://user-images.githubusercontent.com/122573313/216776945-56162416-f2b7-4154-8aea-5976d81d9145.png">

At the end of all of those installs I get this...

Please any help is extremely appreciated! I feel like I might need to just uninstall everything and completely start over but I have no clue where to even start with that. I just wanted to play around with batch img2img to use in my work.

**Comment by stackpanda** [comment]
Try using elevated permissions yeah?

**Comment by ramzillious** [comment]
> Try using elevated permissions yeah?
I'll look it up and see what I can figure out. First time using the terminal so I have no clue what that means haha

**Comment by ramzillious** [comment]
ok so I tried to run the command with sudo in the beginning and it gives me this...
<img width="791" alt="Screenshot 2023-02-06 at 10 19 30 AM" src="https://user-images.githubusercontent.com/122573313/217053595-44d207e7-d53b-46d9-8f3b-8a93b2442793.png">

**Comment by ramzillious** [comment]
I tried running auto111 on google colab and got through to the point where it popped out the link finally then I go to the link and it gives me this...
<img width="1519" alt="Screenshot 2023-02-06 at 1 12 39 PM" src="https://user-images.githubusercontent.com/122573313/217090583-792b57e0-0367-46b7-b66b-835b58116ea8.png">


Feel like im going a little crazy honestly haha

**Comment by ramzillious** [comment]
This is the code. It is still running the process so Im not sure if its not done and I'm just being impatient. I just saw the link pop up and thought it was done. The link does look completely different than anything im seeing other people get though.
<img width="1179" alt="Screenshot 2023-02-06 at 1 16 38 PM" src="https://user-images.githubusercontent.com/122573313/217090695-6582b6b2-c5b2-4b23-97db-4b0ea0ec91af.png">

**Comment by ramzillious** [comment]
I ran it the same exact method with SD 2.1 and it worked!

**Comment by jenuk** [comment]
From the error-message I am assuming your question is about the [stable diffusion webui by AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui). Please be aware this is a third-party tool and we cannot provide any support for it. You may want to look into the [issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue) there, both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.
