### ISSUE TITLE
I NEED HELP. IVE DOWNLOADED PYTHON 3.10.6 AND FOLLOWED THE GUIDE AND THIS KEEPS POPPING UP

### ISSUE THREAD

**Issue by TheFoxiez** [CompVis/stable-diffusion#608]
![IMG_1454](https://user-images.githubusercontent.com/60009970/218318882-e2188d31-eb3b-4f45-97b9-dc3fe57c99f7.jpg)
![IMG_1453](https://user-images.githubusercontent.com/60009970/218318887-a3b12443-ef34-424a-9ab2-db0d09adc825.jpg)

**Comment by TheFoxiez** [comment]
@asanakoy

**Comment by FurkanGozukara** [comment]
@TheFoxiez 

1.) Automatic1111 Web UI
[Easiest Way to Install & Run Stable Diffusion Web UI on PC by Using Open Source Automatic Installer](https://www.youtube.com/watch?v=AZg6vzWHOTA)
image

2.) Automatic1111 Web UI
[How to use Stable Diffusion V2.1 and Different Models in the Web UI - SD 1.5 vs 2.1 vs Anything V3](https://www.youtube.com/watch?v=aAyvsX-EpG4)
image

moreover if you get error in a fresh installation of automatic1111

find this file : requirements_versions.txt

add this to the very end of the file

fastapi==0.90.1

**Comment by TheFoxiez** [comment]
I tried the last one but its already there

**Comment by TheFoxiez** [comment]
> @TheFoxiez
> 
> 1.) Automatic1111 Web UI [Easiest Way to Install & Run Stable Diffusion Web UI on PC by Using Open Source Automatic Installer](https://www.youtube.com/watch?v=AZg6vzWHOTA) image
> 
> 2.) Automatic1111 Web UI [How to use Stable Diffusion V2.1 and Different Models in the Web UI - SD 1.5 vs 2.1 vs Anything V3](https://www.youtube.com/watch?v=aAyvsX-EpG4) image
> 
> moreover if you get error in a fresh installation of automatic1111
> 
> find this file : requirements_versions.txt
> 
> add this to the very end of the file
> 
> fastapi==0.90.1

I just did this today didnt work

**Comment by FurkanGozukara** [comment]
> > @TheFoxiez
> > 1.) Automatic1111 Web UI [Easiest Way to Install & Run Stable Diffusion Web UI on PC by Using Open Source Automatic Installer](https://www.youtube.com/watch?v=AZg6vzWHOTA) image
> > 2.) Automatic1111 Web UI [How to use Stable Diffusion V2.1 and Different Models in the Web UI - SD 1.5 vs 2.1 vs Anything V3](https://www.youtube.com/watch?v=aAyvsX-EpG4) image
> > moreover if you get error in a fresh installation of automatic1111
> > find this file : requirements_versions.txt
> > add this to the very end of the file
> > fastapi==0.90.1
> 
> I just did this today didnt work

this is not necessary anymore it is fixed

i say try a fresh install use python 3.10.6

**Comment by TheFoxiez** [comment]
> > > @TheFoxiez
> > > 1.) Automatic1111 Web UI [Easiest Way to Install & Run Stable Diffusion Web UI on PC by Using Open Source Automatic Installer](https://www.youtube.com/watch?v=AZg6vzWHOTA) image
> > > 2.) Automatic1111 Web UI [How to use Stable Diffusion V2.1 and Different Models in the Web UI - SD 1.5 vs 2.1 vs Anything V3](https://www.youtube.com/watch?v=aAyvsX-EpG4) image
> > > moreover if you get error in a fresh installation of automatic1111
> > > find this file : requirements_versions.txt
> > > add this to the very end of the file
> > > fastapi==0.90.1
> > 
> > 
> > I just did this today didnt work
> 
> this is not necessary anymore it is fixed
> 
> i say try a fresh install use python 3.10.6

I deleted everything and re did it and it still did not work

**Comment by FurkanGozukara** [comment]
> > > > @TheFoxiez
> > > > 1.) Automatic1111 Web UI [Easiest Way to Install & Run Stable Diffusion Web UI on PC by Using Open Source Automatic Installer](https://www.youtube.com/watch?v=AZg6vzWHOTA) image
> > > > 2.) Automatic1111 Web UI [How to use Stable Diffusion V2.1 and Different Models in the Web UI - SD 1.5 vs 2.1 vs Anything V3](https://www.youtube.com/watch?v=aAyvsX-EpG4) image
> > > > moreover if you get error in a fresh installation of automatic1111
> > > > find this file : requirements_versions.txt
> > > > add this to the very end of the file
> > > > fastapi==0.90.1
> > > 
> > > 
> > > I just did this today didnt work
> > 
> > 
> > this is not necessary anymore it is fixed
> > i say try a fresh install use python 3.10.6
> 
> I deleted everything and re did it and it still did not work

i dont see why not working

there is 1 more thing you can do. delete cache folder

go cache and inside cache delete hugging face

**Comment by TheFoxiez** [comment]
> > > > > @TheFoxiez
> > > > > 1.) Automatic1111 Web UI [Easiest Way to Install & Run Stable Diffusion Web UI on PC by Using Open Source Automatic Installer](https://www.youtube.com/watch?v=AZg6vzWHOTA) image
> > > > > 2.) Automatic1111 Web UI [How to use Stable Diffusion V2.1 and Different Models in the Web UI - SD 1.5 vs 2.1 vs Anything V3](https://www.youtube.com/watch?v=aAyvsX-EpG4) image
> > > > > moreover if you get error in a fresh installation of automatic1111
> > > > > find this file : requirements_versions.txt
> > > > > add this to the very end of the file
> > > > > fastapi==0.90.1
> > > > 
> > > > 
> > > > I just did this today didnt work
> > > 
> > > 
> > > this is not necessary anymore it is fixed
> > > i say try a fresh install use python 3.10.6
> > 
> > 
> > I deleted everything and re did it and it still did not work
> 
> i dont see why not working
> 
> there is 1 more thing you can do. delete cache folder
> 
> go cache and inside cache delete hugging face

I tried looking for a cache folder but i dont have one ill send a picture of which ones i do have

**Comment by TheFoxiez** [comment]
![IMG_1473](https://user-images.githubusercontent.com/60009970/218554177-005d31df-693f-4171-b83c-0896e6c82e85.jpg)
![IMG_1474](https://user-images.githubusercontent.com/60009970/218554218-db58590f-742a-490e-929e-895aa08a552d.jpg)

**Comment by p2rdik** [comment]
Windows+Shift+S thank me later. Instead of using your phone to take screenshots.

> ![IMG_1473](https://user-images.githubusercontent.com/60009970/218554177-005d31df-693f-4171-b83c-0896e6c82e85.jpg) ![IMG_1474](https://user-images.githubusercontent.com/60009970/218554218-db58590f-742a-490e-929e-895aa08a552d.jpg)

**Comment by jenuk** [comment]
From the error-message I am assuming your question is about the [stable diffusion webui by AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui). Please be aware this is a third-party tool and we cannot provide any support for it. You may want to look into the [issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue) there, both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.
