### ISSUE TITLE
Please help me run stable diffusion 

### ISSUE THREAD

**Issue by Alexkor2020** [CompVis/stable-diffusion#622]
D:\stable diffusion\stable-diffusion-webui>git pull
fatal: detected dubious ownership in repository at 'D:/stable diffusion/stable-diffusion-webui'
'D:/stable diffusion/stable-diffusion-webui' is on a file system that doesnot record ownership
To add an exception for this directory, call:

        git config --global --add safe.directory 'D:/stable diffusion/stable-diffusion-webui'

D:\stable diffusion\stable-diffusion-webui>pause
Для продолжения нажмите любую клавишу . . .
venv "D:\stable diffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: <none>
Traceback (most recent call last):
  File "D:\stable diffusion\stable-diffusion-webui\launch.py", line 360, in <module>
    prepare_environment()
  File "D:\stable diffusion\stable-diffusion-webui\launch.py", line 300, in prepare_environment
    git_clone(stable_diffusion_repo, repo_dir('stable-diffusion-stability-ai'), "Stable Diffusion", stable_diffusion_commit_hash)
  File "D:\stable diffusion\stable-diffusion-webui\launch.py", line 151, in git_clone
    current_hash = run(f'"{git}" -C "{dir}" rev-parse HEAD', None, f"Couldn't determine {name}'s hash: {commithash}").strip()
  File "D:\stable diffusion\stable-diffusion-webui\launch.py", line 105, in run
    raise RuntimeError(message)
RuntimeError: Couldn't determine Stable Diffusion's hash: 47b6b607fdd31875c9279cd2f4f16b92e4ea958e.
Command: "git" -C "repositories\stable-diffusion-stability-ai" rev-parse HEAD
Error code: 128
stdout: <empty>
stderr: fatal: detected dubious ownership in repository at 'D:/stable diffusion/stable-diffusion-webui/repositories/stable-diffusion-stability-ai'
'D:/stable diffusion/stable-diffusion-webui/repositories/stable-diffusion-stability-ai' is on a file system that doesnot record ownership
To add an exception for this directory, call:

        git config --global --add safe.directory 'D:/stable diffusion/stable-diffusion-webui/repositories/stable-diffusion-stability-ai'

**Comment by Zefionth** [comment]
i had same problem, you should open Git Bash and enter command  `git config --global~ (last line)` there and close. then run webui-user.bat again and if it asks to call some command again to add an exception for directory then repeat previous steps. i was supposed to do this 3 times

**Comment by Sergiclg** [comment]
I had a very similar if not identical error and found the solution. Steps to follow:

1. Open the Start menu and look for "Environment Variables".
2. Select "Edit system environment variables".
3. Click the "Environment Variables" button.
4. In the "System Variables" section, find the PATH variable and click the "Edit" button.
5. Click the "New" button and add the path to the git application (e.g. "C:\Program Files\Git\bin").
6. Click "OK" to save your changes and close all windows.

Once you have added the git application path to the PATH environment variable, try running the .bat file again. I hope this helps you fix the problem.

Curiosity: Chat GPT solved it for me, because I had no idea. :-)

**Comment by jenuk** [comment]
From the error-message I am assuming your question is about the [stable diffusion webui by AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui). Please be aware this is a third-party tool and we cannot provide any support for it. You may want to look into the [issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue) there, both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.

**Comment by fuqifacai** [comment]
Just run
git config --global --add safe.directory '*'
to disable this warning . it works for me.
