### ISSUE TITLE
"message": "Reduce init_image resolution"

### ISSUE THREAD

**Issue by jDimmy** [CompVis/stable-diffusion#625]
Hi,
I'm using the stable diffusion image to image [API](https://stablediffusionapi.com/docs/features/image-to-image). It works well with that image in the documentation.

But, when I use another image (from my computer or anywhere else), I get this :

`
{
    "status": "failed",
    "id": "",
    "message": "Reduce init_image resolution",
    "output": ""
}

`

Can someone help me solve this ?

**Comment by jenuk** [comment]
That website/company is not associated with us. You need to ask them for help.
