### ISSUE TITLE
Issue Cloning stable-diffusion-webui

### ISSUE THREAD

**Issue by idbayless** [CompVis/stable-diffusion#634]
Hey all, I was wondering if anyone can help me with an issue I am having. I should put out up front that I am pretty new to how GitHub and how it works.

I am inputting the following command into Git Bash :  $ git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui.git

I then get the following error:

Cloning into 'stable-diffusion-webui'...
fatal: unable to access 'https://github.com/AUTOMATIC1111/stable-diffusion-webui.git/': Connection timeout after 300000 ms

Does anyone have any idea why this may be occurring?

**Comment by linchangting** [comment]
waiting for some solutions....

**Comment by jenuk** [comment]
Seems like there is an issue with your internet connection.

However, from the error-message I am assuming your question is about the [stable diffusion webui by AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui). Please be aware this is a third-party tool and we cannot provide any support for it. You may want to look into the [issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue) there, both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.
