### ISSUE TITLE
/

### ISSUE THREAD

**Issue by rerere14** [CompVis/stable-diffusion#641]
pls help what to do
FileNotFoundError: You need to download the Stable Diffusion model in order to use the UI.

**Comment by jenuk** [comment]
From the error-message I am assuming your question is about the [stable diffusion webui by AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui). Please be aware this is a third-party tool and we cannot provide any support for it. You may want to look into the [issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue) there, both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.
