### ISSUE TITLE
Cannot import name 'open_code' from 'io'

### ISSUE THREAD

**Issue by retrosymmetry** [CompVis/stable-diffusion#649]
Hi, every time I try launching the webui-user.bat file, python runs into the following error

"
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Traceback (most recent call last):

line 54, in <module>
ImportError: cannot import name 'open_code' from 'io' (unknown location)
Press any key to continue . . .
"

Im a bit of a novice when it comes to python, but ive ensured stab diffusion is all installed correctly (though have been unable to launch so far), and that pyhton is on the correct ver (3.10 64 bit)- as well as python path and home being correctly set.

**Comment by jenuk** [comment]
From the error-message I am assuming your question is about the [stable diffusion webui by AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui). Please be aware this is a third-party tool and we cannot provide any support for it. You may want to look into the [issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue) there, both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.
