### ISSUE TITLE
Math Typo in Paper (dimension of linear layers in Q, K, V)

### ISSUE THREAD

**Issue by RoyVoetman** [CompVis/stable-diffusion#651]
I am reading the latent diffusion paper, which states for cross-attention we have a linear projection for Q K V with W_q W_k W_v. 

But it then says W_v \in R^{d x d_c^i} and both W_q and W_k \in R^{d x d_r}. But shouldn't W_q be \in R^{d x d_c^i} and W_v \in R^{d x d_r}? Since K and V need to have the same dimension? By looking at the code here on github W_v and W_k are also of the same dim, but as I said not in the paper? Is this a known typo?

Paper:
![image](https://user-images.githubusercontent.com/23026444/223661011-dea18252-b895-424f-b3d8-a58ab923cb9e.png)

![image](https://user-images.githubusercontent.com/23026444/223661096-f015ccd3-2131-4765-9647-0a8235f3188b.png)

Code:
![image](https://user-images.githubusercontent.com/23026444/223661173-651fcd9b-0a7a-4f6d-9572-024b980f87d8.png)

https://github.com/CompVis/stable-diffusion/blob/21f890f9da3cfbeaba8e2ac3c425ee9e998d5229/ldm/modules/attention.py#L152

**Comment by jenuk** [comment]
You are right, this is a typo. The indexes of $W_V$ and $W_Q$ are swapped and I believe there are some transposition-issues. You could change it to this and it should be correct: $W_Q \in \mathbb R^{d_\epsilon \times d}, W_K \in \mathbb R^{d_\tau \times d}$, and $W_V \in \mathbb R^{d_\tau \times d}$. As well as

$$
  Q = \varphi(z_t) \cdot W_Q  \in \mathbb R^{N \times d}
$$

$$
  K = \tau(y)  \cdot W_K \in \mathbb R^{M \times d}
$$


$$
  V = \tau(y)  \cdot W_V \in \mathbb R^{M \times d}
$$

Thanks for pointing that out!
