### ISSUE TITLE
Couldn't install gfpgan when installing Webui

### ISSUE THREAD

**Issue by AkMesitochito** [CompVis/stable-diffusion#660]
RuntimeError: Couldn't install gfpgan.
Command: "D:\elfinal\novelaileak\stable-diffusion-webui\venv\Scripts\python.exe" -m pip install git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379 --prefer-binary
Error code: 1
stdout: Collecting git+https://github.com/TencentARC/GFPGAN.git@8d2447a2d918f8eba5a4a01463fd48e45126a379
  Cloning https://github.com/TencentARC/GFPGAN.git (to revision 8d2447a2d918f8eba5a4a01463fd48e45126a379) to c:\users\usuario\appdata\local\temp\pip-req-build-ey5do_yn

stderr:   ERROR: Error [WinError 2] The system could not fin the file while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

I have python 3.10.6 and i tried with 3.10.10 but it was the same mistake, what i should do?

**Comment by jenuk** [comment]
From the error-message I am assuming your question is about the [stable diffusion webui by AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui). Please be aware this is a third-party tool and we cannot provide any support for it. You may want to look into the [issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue) there, both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.
