### ISSUE TITLE
Python Launch error

### ISSUE THREAD

**Issue by nanochad09** [CompVis/stable-diffusion#663]
I am not a coder, followed every step to set up Stable Diffusion, but when I tried to run "webui-user.bat", the command window showed me this lines below,

Couldn't launch python

exit code: 9009

stderr:
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

Launch unsuccessful. Exiting.
Press any key to continue . . .

any solution geeks??

**Comment by gtgtgt1117** [comment]
install anaconda or miniconda, then run the command "conda env create -f environment.yaml"

**Comment by jenuk** [comment]
You haven't installed python or it is not referenced in your path. However, from the error-message I am assuming your question is about the [stable diffusion webui by AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui). Please be aware this is a third-party tool and we cannot provide any support for it. You may want to look into the [issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue) there, both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.
