### ISSUE TITLE
ImportError: cannot import name 'SAFE_WEIGHTS_NAME' from 'transformers.utils'

### ISSUE THREAD

**Issue by wangyp33** [CompVis/stable-diffusion#668]
Traceback (most recent call last):
  File "scripts/txt2img.py", line 22, in <module>
    from diffusers.pipelines.stable_diffusion.safety_checker import StableDiffusionSafetyChecker
  File "/share/home/softrh05/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/__init__.py", line 27, in <module>
    from .pipelines import OnnxRuntimeModel
  File "/share/home/softrh05/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/__init__.py", line 18, in <module>
    from .dance_diffusion import DanceDiffusionPipeline
  File "/share/home/softrh05/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/dance_diffusion/__init__.py", line 1, in <module>
    from .pipeline_dance_diffusion import DanceDiffusionPipeline
  File "/share/home/softrh05/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/dance_diffusion/pipeline_dance_diffusion.py", line 21, in <module>
    from ..pipeline_utils import AudioPipelineOutput, DiffusionPipeline
  File "/share/home/softrh05/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 64, in <module>
    from transformers.utils import SAFE_WEIGHTS_NAME as TRANSFORMERS_SAFE_WEIGHTS_NAME
ImportError: cannot import name 'SAFE_WEIGHTS_NAME' from 'transformers.utils' (/share/home/softrh05/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/utils/__init__.py)

**Comment by lecuek** [comment]
Hi, I had this issue and this https://github.com/CompVis/stable-diffusion/issues/627 helped me!

**Comment by gtgtgt1117** [comment]
uninstall transformers and reinstall transformers==4.27.1.

**Comment by gtgtgt1117** [comment]
> uninstall transformers and reinstall transformers==4.27.1.



> Traceback (most recent call last): File "scripts/txt2img.py", line 22, in from diffusers.pipelines.stable_diffusion.safety_checker import StableDiffusionSafetyChecker File "/share/home/softrh05/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/**init**.py", line 27, in from .pipelines import OnnxRuntimeModel File "/share/home/softrh05/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/**init**.py", line 18, in from .dance_diffusion import DanceDiffusionPipeline File "/share/home/softrh05/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/dance_diffusion/**init**.py", line 1, in from .pipeline_dance_diffusion import DanceDiffusionPipeline File "/share/home/softrh05/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/dance_diffusion/pipeline_dance_diffusion.py", line 21, in from ..pipeline_utils import AudioPipelineOutput, DiffusionPipeline File "/share/home/softrh05/anaconda3/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/pipeline_utils.py", line 64, in from transformers.utils import SAFE_WEIGHTS_NAME as TRANSFORMERS_SAFE_WEIGHTS_NAME ImportError: cannot import name 'SAFE_WEIGHTS_NAME' from 'transformers.utils' (/share/home/softrh05/anaconda3/envs/ldm/lib/python3.8/site-packages/transformers/utils/**init**.py)

uninstall transformers and reinstall transformers==4.27.1.
