### ISSUE TITLE
stable diffusion exports dontt appear on my drive

### ISSUE THREAD

**Issue by 1000a1000a** [CompVis/stable-diffusion#669]
Hi! It's the first time that happens to me, but everything I export from stable diffusion does not appear in my drive in any way and in any place, I tried to restart google collab, close my drive, download and upload the model again but still no export appears in the deforum folder.

**Comment by jenuk** [comment]
I'm assuming you are asking about the [deforum notebook](https://github.com/deforum-art/deforum-stable-diffusion). If you have any issues with that, please ask them on that repository.
