### ISSUE TITLE
issue ruining this python code >phyton save_onnx.py

### ISSUE THREAD

**Issue by lefty55555** [CompVis/stable-diffusion#672]
File "C:\Users\carel\OneDrive\Desktop\PythoninOffice\stable_diffusion_amd\diffusers-dml\examples\inference\save_onnx.py", line 16, in <module>
    pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", scheduler=lms, use_auth_token=True)
  File "C:\Users\carel\OneDrive\Desktop\PythoninOffice\stable_diffusion_amd\diffusers-dml\src\diffusers\pipeline_utils.py", line 241, in from_pretrained
    load_method = getattr(class_obj, load_method_name)
AttributeError: type object 'PNDMScheduler' has no attribute 'from_pretrained'

**Comment by jenuk** [comment]
From the error-message I am assuming your question is about the [huggingface diffusers library](https://github.com/huggingface/diffusers/). Please be aware this is an independent codebase and we cannot provide any support for it. You may want to look into the [issues](https://github.com/huggingface/diffusers/issues?q=is%3Aissue) there, both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.
