### ISSUE TITLE
webui-user.bat not there

### ISSUE THREAD

**Issue by TTionnn** [CompVis/stable-diffusion#673]
I've been trying to install stable-diffusion a1111 and everything I've looked at says you just have to open webui-user.bat, but for me this doesn't appear even after reinstalling the whole thing. I'm not sure what else to try and I cant find anything about this issue anywhere else.
![explorer_jpW2tn2nW0](https://user-images.githubusercontent.com/128680652/227134283-ba66fee2-d7a1-49d2-8bff-ba310f35c714.png)

**Comment by YvetteLareina** [comment]
Hello With me it is the same, does anyone know why this is so? And is there a solution to this?

**Comment by Billiva** [comment]
"webui-user.bat" it's above the last one on this picture you showed.

### **webui-user  __________ 3/23/2023____________ 2:19 AM__________ WINDOWS BATCH FILE__________ 1KB**

**Comment by jenuk** [comment]
From the error-message I am assuming your question is about the [stable diffusion webui by AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui). Please be aware this is a third-party tool and we cannot provide any support for it. You may want to look into the [issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue) there both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.
