### ISSUE TITLE
Command window closes after this message and I can't run 

### ISSUE THREAD

**Issue by Noel750** [CompVis/stable-diffusion#678]
[+] bitsandbytes version 0.35.0 installed.
[ ] diffusers version 0.9.0 installed.
[+] transformers version 4.21.0 installed.
[+] torch version 1.12.1+cu116 installed.
[+] torchvision version 0.13.1+cu116 installed.
[!] xformers NOT installed.

Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
==============================================================================
You are running torch 1.12.1+cu116.
The program is tested to work with torch 1.13.1.
To reinstall the desired version, run with commandline flag --reinstall-torch.
Beware that this will cause a lot of large files to be downloaded, as well as
there are reports of issues with training tab on the latest version.

Use --skip-version-check commandline argument to disable this check.
==============================================================================
Dreambooth API layer loaded
Loading weights [1254103966] from C:\Users\Noel\Desktop\Stable_diffusion\stable-diffusion-webui\models\Stable-diffusion\protogenV22Anime_22.safetensors
Creating model from config: C:\Users\Noel\Desktop\Stable_diffusion\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying cross attention optimization (Doggettx).
Textual inversion embeddings loaded(1): durer-style
Model loaded in 13.9s (load weights from disk: 0.2s, create model: 0.6s, apply weights to model: 9.6s, apply half(): 0.8s, move model to device: 0.7s, load textual inversion embeddings: 2.0s).
Traceback (most recent call last):
  File "C:\Users\Noel\Desktop\Stable_diffusion\stable-diffusion-webui\launch.py", line 356, in <module>
    start()
  File "C:\Users\Noel\Desktop\Stable_diffusion\stable-diffusion-webui\launch.py", line 351, in start
    webui.webui()
  File "C:\Users\Noel\Desktop\Stable_diffusion\stable-diffusion-webui\webui.py", line 243, in webui
    shared.demo = modules.ui.create_ui()
  File "C:\Users\Noel\Desktop\Stable_diffusion\stable-diffusion-webui\modules\ui.py", line 448, in create_ui
    with gr.Blocks(analytics_enabled=False) as txt2img_interface:
  File "C:\Users\Noel\Desktop\Stable_diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 535, in __init__
    super().__init__(render=False, **kwargs)
  File "C:\Users\Noel\Desktop\Stable_diffusion\stable-diffusion-webui\modules\scripts.py", line 561, in BlockContext_init
    add_classes_to_gradio_component(self)
  File "C:\Users\Noel\Desktop\Stable_diffusion\stable-diffusion-webui\modules\scripts.py", line 529, in add_classes_to_gradio_component
    comp.elem_classes = ["gradio-" + comp.get_block_name(), *(comp.elem_classes or [])]
AttributeError: 'Blocks' object has no attribute 'elem_classes'
Press any key to continue . . .

**Comment by jenuk** [comment]
From the error-message I am assuming your question is about the [stable diffusion webui by AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui). Please be aware this is a third-party tool and we cannot provide any support for it. You may want to look into the [issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue) there both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.
