### ISSUE TITLE
Could not allocate tensor with, RX480 8GB

### ISSUE THREAD

**Issue by Kerber0ss** [CompVis/stable-diffusion#687]
Hello, i have AMD RX480 with 8GB memory.
Run with this manual on Windows https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs
model sd-v1-4.ckpt
But get these Warning at start:
```
Warning: experimental graphic memory optimization is disabled due to gpu vendor. Currently this optimization is only available for AMDGPUs.
Disabled experimental graphic memory optimizations.
Interrogations are fallen back to cpu. This doesn't affect on image generation. But if you want to use interrogate (CLIP or DeepBooru), check out this issue: https://github.com/lshqqytiger/stable-diffusion-webui-directml/issues/10
Warning: caught exception 'Torch not compiled with CUDA enabled', memory monitor disabled
No module 'xformers'. Proceeding without it.
```

And these error at 50% Generate

```
RuntimeError: Could not allocate tensor with 9850880 bytes. There is not enough GPU video memory available!
```
Run with this flags
```
COMMANDLINE_ARGS=--precision full --no-half
```
or without, error persist.
How to fix this?

**Comment by jenuk** [comment]
From the error-message I am assuming your question if about the [stable diffusion webui by AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui). Please be aware this is a third-party tool and we cannot provide any support for it. You may want to look into the [issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue) there both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.
