### ISSUE TITLE
Stuck DiffusionWrapper has 859.52 M params.

### ISSUE THREAD

**Issue by DCCross** [CompVis/stable-diffusion#688]
Hello, could someone give me a hand? I'm starting with "stable diffusion" and at boot time it gets stuck at 
"DiffusionWrapper has 859.52 M params."
![image](https://user-images.githubusercontent.com/60871026/230143349-9e6e3fb4-595c-4818-9fd2-a7f22a76d903.png)

I have used the installer and more solutions such as clearing the cache, using the installer and pressing enter but it still does not advance.

I really don't know what I'm doing wrong

**Comment by Jonathanzero93** [comment]
i have the same problem Let me know if you can fix it

**Comment by jenuk** [comment]
From the error-message I am assuming your question if about the [stable diffusion webui by AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui). Please be aware this is a third-party tool and we cannot provide any support for it. You may want to look into the [issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue) there both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.
