### ISSUE TITLE
Hi. When I start the program, the installation does not end, freezes and stops updating.

### ISSUE THREAD

**Issue by eJuiceeN** [CompVis/stable-diffusion#689]
I followed the guide, but something went wrong

Writes on the cmd:

_E:\Program\Stable-Diffusion\stable-diffusion-webui>git pull
Already up to date.
venv "E:\Program\Stable-Diffusion\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI
Launching Web UI with arguments:
No module 'xformers'. Proceeding without it.
Loading weights [e1441589a6] from E:\Program\Stable-Diffusion\stable-diffusion-webui\models\Stable-diffusion\model.ckpt
Creating model from config: E:\Program\Stable-Diffusion\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params._

I waited long enough, thinking that it would take time, but it did not help. The problem is definitely not in the performance of the computer. I reinstalled, registered commands, but nothing really changed. It just stops.

I will be glad for your help
____________________________________________________________________________________________________________________________

**As stupid as it sounds, it fixed itself the next day.**

**Comment by Jonathanzero93** [comment]
i have the same problem Let me know if you can fix it

**Comment by jenuk** [comment]
From the error-message I am assuming your question if about the [stable diffusion webui by AUTOMATIC1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui). Please be aware this is a third-party tool and we cannot provide any support for it. You may want to look into the [issues](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues?q=is%3Aissue) there both closed and open to find out if other people have reported this problem before, or open a new issue if that is not the case.

**Comment by eJuiceeN** [comment]
> 

As stupid as it sounds, it fixed itself the next day.
