### ISSUE TITLE
Why not archive this buggy repo ?

### ISSUE THREAD

**Issue by HuangChiEn** [CompVis/stable-diffusion#708]
The hugging face can already download the pre-trained SD model (released from this repo). 

On the other hand, the training code is full of buggy in this repo and users barely find the training code. It's meaningless to directly release this repo on GitHub, so why don't you guys just archive this repo for telling any potential user that this repo is only usable and that we're not going to maintain it?

**Comment by CreamyLong** [comment]
I feel the same and I have been rebuilding this [repo](https://github.com/CreamyLong/stable-diffusion).

**Comment by HuangChiEn** [comment]
> I feel the same and I have been rebuilding this [repo](https://github.com/CreamyLong/stable-diffusion).

you guys should thank this guy who did you'll a big favor ~
