### ISSUE TITLE
Intel Arc GPU supported?

### ISSUE THREAD

**Issue by leeksoup** [CompVis/stable-diffusion#720]
Will this software work with an Intel Arc A770 GPU? I didn't see any info on that in the issues. Thanks

**Comment by leeksoup** [comment]
Does anyone know the answer to whether Intel Arc GPU is supported? Thanks

**Comment by aidan-middleton** [comment]
You are able to run Stable diffusion on intel arc GPUs. Intel has an official page on this topic. I recommend you take a look at it. https://www.intel.com/content/www/us/en/developer/articles/technical/running-tensorflow-stable-diffusion-on-intel-arc.html#gs.ztvfaz

**Comment by leeksoup** [comment]
@aidan-middleton - Thank you! I will check that out.
