### ISSUE TITLE
How to run it from a .BAT file

### ISSUE THREAD

**Issue by pdavis68** [CompVis/stable-diffusion#734]
Can someone shed some light on how I can run this from a batch file? Specifically, I'm trying to run it from within a C# application (using a Process.Start() call). I figured I could do something like:

set args=%*
conda env create -f environment.yaml
conda activate ldm 
python scripts/txt2img.py --prompt %args% --ckpt checkpoints\sd-v1-4.ckpt --n_samples 1 --ddim_steps 25 --plms

within the .BAT file, but that doesn't seem to work at all. 

I've tried several variations, but can't seem to come up with a solution. Would appreciate any help.

**Comment by hackthedev** [comment]
I have a batch file in the directory of stable diffusions root and use it like this
```
title Stable Deffusion Auto
color 0b

:start
docker compose --profile auto up --build
pause
goto start
```
