### ISSUE TITLE
[Suggestion] embed the prompt to images as metadata

### ISSUE THREAD

**Issue by junguler** [CompVis/stable-diffusion#74]
the first thing everyone talks about after seeing an image made with SD and how amazing it looks is what was the prompt used, so why not automatically embed these to the png files so the people who want it have access to it already

**Comment by leszekhanusz** [comment]
Good idea!

**Comment by darthdeus** [comment]
This would be good even when not counting image sharing. I think most of us already created a bunch of wrappers that log the prompts/parameters/seeds along with the images, which gets a bit annoying as images are moved around and/or shared.

I haven't tested this yet, but this is probably what we want https://stackoverflow.com/a/58399815, simply storing the metadata in the PNG.
