### ISSUE TITLE
Why occurs Never Gonna Give You Up?????

### ISSUE THREAD

**Issue by xiao10ma** [CompVis/stable-diffusion#873]
I use the prompt "a photograph of a cartoon horse" to generate a horse image, but it occurs the song "Why occurs Never Gonna Give You Up"
![grid-0003](https://github.com/user-attachments/assets/033e989e-71c6-4b63-aefa-6fe369ba200c)

**Comment by s1m0n32001** [comment]
Quite a funny easter egg! It  occurs when the StableDiffusionSafetyChecker thinks that the generated image has NSFW content.
You can find it at line 317 of scripts/txt2img.py

**Comment by xiao10ma** [comment]
Wow, that's so funny! hahaha
