### ISSUE TITLE
No module named 'ldm.util'; 'ldm' is not a package

### ISSUE THREAD

**Issue by kechan** [CompVis/stable-diffusion#92]
I tried "python scripts/txt2img.py --prompt "a photograph of an astronaut riding a horse" --plms --ckpt ~/tmp/sd-v1-4.ckpt --skip_grid --n_sample 1"

but got this (in addition to "Error when calling Cognitive Face API"

Traceback (most recent call last):
  File "scripts/txt2img.py", line 17, in <module>
    from ldm.util import instantiate_from_config
ModuleNotFoundError: No module named 'ldm.util'; 'ldm' is not a package

**Comment by junukwon7** [comment]
Did you activate your own conda env? It should be installed by the command below while creating the ldm environment.
```
pip install -e git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers
pip install -e git+https://github.com/openai/CLIP.git@main#egg=clip
pip install -e .
```

**Comment by kechan** [comment]
@junukwon7 My bad. I didnt use conda env , and am using virtualenv + pip and just pip install whatever it complained missing. I must have messed things up along the way. 

Do we have to run this using conda? but not virtualenv

**Comment by junukwon7** [comment]
> @junukwon7 My bad. I didnt use conda env , and am using virtualenv + pip and just pip install whatever it complained missing. I must have messed things up along the way.
> 
> Do we have to run this using conda? but not virtualenv

I'm not sure. However, it seems like all the environments are pre-configured to well operate with conda, so I recommend you to do so too :)

**Comment by kechan** [comment]
@junukwon7 I actually found a ldm/util.py, it must have landed there among the pip install i did manually (including ldm). the ldm directory is missing __init__, thus it isnt recognized as package. Fixing that, and moving the script txt2img.py one dir up, i am able to get past the complaints.

Yes, I should have done this in Conda, I am verifying this on colab. 

I will still see if i can get it to run without Conda (I now got to PLMS Sampler part, it is very slow on my local laptop).

**Comment by junukwon7** [comment]
Nice to hear you solved your issue. However, I would like to inform you one thing:
```pip install -e .``` should be performed in the root directory(stable-diffusion) of the project, not inside the ldm since the installation information is stored in ```setup.py```. If you already know this, just ignore my reply.

Also, I think using it without conda would also have no problem since stablediffusion doesn't seem to have harsh nor sensitive dependencies. If you're working on a Nvidia CUDA environment, there shall be no major issues.

**Comment by kechan** [comment]
@junukwon7 Thanks for your guidance. 

I somehow got it all to work: virtualenv+pip (no conda), on macbook air OS 11.2.3 (CPU only). 
I also did "pip install -e ." under stable-diffusion dir. The ldm dir may have been setup during the install, or whatever. I also have to manually fix the print statement throughout some older modules based on py2?? Not sure why this isn't needed under Conda (i got conda+GPU to work in colab as well). 

But relatively, it still isn't among the hardest to run thing from an AI research github. 

Great thanks to the stable-diffusion team.

**Comment by YS-IMTech** [comment]
> 

I try to  add __init__.py to the ldm directory,but still ouput the same error as u

**Comment by YS-IMTech** [comment]
I try to add __init__.py to the ldm directory,but still ouput the same error as u

**Comment by YS-IMTech** [comment]
> I try to add **init**.py to the ldm directory,but still ouput the same error as u

oh i know,i forget to pip install -e . lol

**Comment by meisa233** [comment]
import sys
sys.path.append('/the/path/to/the/folder/where/ldm/is/located')
