### ISSUE TITLE
Old GPUs with shared memory

### ISSUE THREAD

**Issue by 3412velx** [CompVis/stable-diffusion#95]
How to run StableDiffusion on old GPUs with shared pc memory?
GTX650 1 Gb VRAM, 6 Gb shared RAM, CUDA 3.0  in my case.

**Comment by csunberry** [comment]
You need at least 4GB of VRAM, if not more than that. 

You can run it for free on Hugging Face here: https://huggingface.co/spaces/stabilityai/stable-diffusion or by going to the official beta release on https://beta.dreamstudio.ai/home

**Comment by patrickvonplaten** [comment]
You can get down to ~5-6GB of VRAM with:

```python
from torch import autocast
from diffusers import StableDiffusionPipeline
import torch

pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", use_auth_token=True, revision="fp16", torch_device=torch.float16)

# remove VAE encoder as it's not needed
del pipe.vae.encoder

# now move to GPU which should not consume more than 5GB
pipe.to("cuda")

prompt = "a photo of an astronaut riding a horse on mars"
with autocast("cuda"):
    image = pipe(prompt)["sample"][0] 
```

You can get even lower (3-4GB VRAM) if you move the safety checker on CPU

**Comment by 3412velx** [comment]
> You need at least 4GB of VRAM, if not more than that.
> 
> You can run it for free on Hugging Face here: https://huggingface.co/spaces/stabilityai/stable-diffusion or by going to the official beta release on https://beta.dreamstudio.ai/home

Thanks for the advice!

**Comment by 3412velx** [comment]
Thank you Patrick.
      But there is another problem. The current versions of Cudatoolkit and Pytorch do not support GTX650. Apparently it is necessary to downgrade the versions of the libraries in the .yaml file. But I don't know what versions for my GPU should be written in this file. I would be grateful for advice on this matter. And one more question. Is it possible to run StableDiffusion only on CPU and how to do it?

**Comment by patrickvonplaten** [comment]
Hmm regarding the versions I don't really know sadly

**Comment by 3412velx** [comment]
> 

OK. Thanks. 
There is another method method here:  https://github.com/bes-dev/stable_diffusion.openvino  But it takes a long (30s to 4min) time per one 512x512 image generation with modern CPUs. Looks like I need to buy a new video card :)

**Comment by rjamesnw** [comment]
> Yes you can run Stable Diffusion on CPU just by doing the following:
> 
> ```python
> from torch import autocast
> from diffusers import StableDiffusionPipeline
> import torch
> 
> pipe = StableDiffusionPipeline.from_pretrained("CompVis/stable-diffusion-v1-4", use_auth_token=True)
> 
> # remove VAE encoder as it's not needed
> del pipe.vae.encoder
> 
> prompt = "a photo of an astronaut riding a horse on mars"
> with autocast("cuda"):
>     image = pipe(prompt)["sample"][0] 
> ```
> 
> => downloading fp32 weights instead of fp16 and by **not** moving the pipeline to GPU

Is this a change to an existing script, or is this meant to be a new script? If new, where do I place it?

**Comment by AlexisTM** [comment]
@rjamesnw This is a new script you can start like the others, but without argument. The prompt is embedded.

**Comment by Natotela** [comment]
I funded meself a 3070 GPU and I see that while nearly all of its 8gb RAM is used, the utilization seems to be nearly 0% according to Win10's Task Manager. Any thought why is that? What does it mean that dedicated RAM is taken but GPU usage is low?

**Comment by AlexisTM** [comment]
That means you are underutilized.

**Comment by Natotela** [comment]
> That means you are underutilized.

10x, but is that an issue I should fix to make the processing go faster, or does it only mean that GPU utilization works when I have some graphics being rendered live (gaming, streaming), rather than computed in the back?

**Comment by AlexisTM** [comment]
Yes, you could infer it 10x as fast. I have that issue because I do not have enough memory on mine (3.8), so it cannot infer the network because it has to load new part of the network continuously in an inneficient manner.

**Comment by Natotela** [comment]
@AlexisTM Feel free to help a lost noob in reclaiming the power at hand :-D I can stroll around the internet for hours, but my brain's algorithm isn't (yet) developed to directly refine the information I am after :-)

**Comment by sagarppatil020504** [comment]
Hi 
I am using amd m340 gpu and how do i run these models on it and it's not supported by rocm is it possible to do
