### ISSUE TITLE
Regenerate only part of the image

### ISSUE THREAD

**Issue by robinchm** [CompVis/stable-diffusion#98]
`img2img.py` allows me to tweak the image with a prompt, but only at its entirety. I run into a case that I am generally happy with the generated image, but want to regenerate only a small region of it. I try to erase the region to transparent (saved in png format) I wish to regenerate, then rerun with the same prompt.

However the erased region seems to be treated as black color so the output is not very desirable. With a small strength, the region is turned into a black block; with a large strength, the entire image is regenerated.

May I know whether there is a way to regenerate only part of the image? Thanks a lot.

**Comment by yomboprime** [comment]
It seems there is a way: with the ```inpainting.py``` script. I've tried to run it but it needs the file ```models/ldm/inpainting_big/last.ckpt``` and I  don't know where to get it.

You can see in the script code that it wants a parameter ```--in_dir``` where you pass it a path to a folder that contains pairs of images named specially (i.e. 'example.png' and 'example_mask.png'). The mask has the part that you want to keep in white, and the rest in black. You can see example images here: https://github.com/CompVis/stable-diffusion/tree/main/data/inpainting_examples

So, we only need that 'last..ckpt' file.

**Comment by robinchm** [comment]
> It seems there is a way: with the `inpaint.py` script. I've tried to run it but it needs the file `models/ldm/inpainting_big/last.ckpt` and I don't know where to get it.
> 
> You can see in the script code that it wants a parameter `--in_dir` where you pass it a path to a folder that contains pairs of images named specially (i.e. 'example.png' and 'example_mask.png'). The mask has the part that you want to keep in black, and the rest in white. You can see example images here: https://github.com/CompVis/stable-diffusion/tree/main/data/inpainting_examples
> 
> So, we only need that 'last.ckpt' file.
> 
> Edit: With the provided download script it does get a zip in 'inpainting_big/', but it does not contain the 'last.ckpt'. Edit2: Found it in this repository (search for 'last'): https://github.com/pesser/stable-diffusion/blob/main/README.md
> 
> Edit3: It works! You have to specify also the `--outdir` param, and optionally the `--steps` one. Edit4: Now I see this script only reconstructs the white parts based on the surroundings. It doesn't accept a prompt. I'm sorry.

Many thanks. I did not even know about the inplant mode.

I'm not familiar with image generation models, but reading through the script it appears that the masking information is encoded in the `conditioning` variable, while in generation mode the prompt is also encoded in the `conditioning` variable. Maybe the model must be trained in the way to accept two kinds of conditioning at the same time for this to work, so it's impossible now, I don't know.

I end up doing the following:
* run `img2img.py` with a large strength, which regenerates the whole image, hoping there is one result with at least similar background color
* crop the area containing the objects I am interested in, resize it and put it into the input image
* regenerate the modified input image with small strength, hoping the model will fix any artifacts

This approach has a main issue that the region of interest must be of relatively simple background, otherwise the artifacts will not be fixed well enough in the last step. The artifacts can turn into some weird "features" in the new image.

Guess this is the best we can do for now?

**Comment by wolfgangmeyers** [comment]
> > It seems there is a way: with the `inpaint.py` script. I've tried to run it but it needs the file `models/ldm/inpainting_big/last.ckpt` and I don't know where to get it.
> > You can see in the script code that it wants a parameter `--in_dir` where you pass it a path to a folder that contains pairs of images named specially (i.e. 'example.png' and 'example_mask.png'). The mask has the part that you want to keep in black, and the rest in white. You can see example images here: https://github.com/CompVis/stable-diffusion/tree/main/data/inpainting_examples
> > So, we only need that 'last.ckpt' file.
> > Edit: With the provided download script it does get a zip in 'inpainting_big/', but it does not contain the 'last.ckpt'. Edit2: Found it in this repository (search for 'last'): https://github.com/pesser/stable-diffusion/blob/main/README.md
> > Edit3: It works! You have to specify also the `--outdir` param, and optionally the `--steps` one. Edit4: Now I see this script only reconstructs the white parts based on the surroundings. It doesn't accept a prompt. I'm sorry.
> 
> Many thanks. I did not even know about the inplant mode.
> 
> I'm not familiar with image generation models, but reading through the script it appears that the masking information is encoded in the `conditioning` variable, while in generation mode the prompt is also encoded in the `conditioning` variable. Maybe the model must be trained in the way to accept two kinds of conditioning at the same time for this to work, so it's impossible now, I don't know.
> 
> I end up doing the following:
> 
> * run `img2img.py` with a large strength, which regenerates the whole image, hoping there is one result with at least similar background color
> * crop the area containing the objects I am interested in, resize it and put it into the input image
> * regenerate the modified input image with small strength, hoping the model will fix any artifacts
> 
> This approach has a main issue that the region of interest must be of relatively simple background, otherwise the artifacts will not be fixed well enough in the last step. The artifacts can turn into some weird "features" in the new image.
> 
> Guess this is the best we can do for now?
> 
> Edit: I found this on the reddit [https://www.reddit.com/r/StableDiffusion/comments/wyduk1/show_rstablediffusion_integrating_sd_in_photoshop/](url), at 0:28 the author indeed generate half of the image with a prompt and the other half unmodified. It's definitely doable while I have no idea how.

Take a look at this. It uses the diffusers library, but it seems to accomplish text-guided inpainting. https://colab.research.google.com/drive/1whhIiXxjQjbBuiq4lqwh-AlLIjh3l1OB

**Comment by robinchm** [comment]
> > > It seems there is a way: with the `inpaint.py` script. I've tried to run it but it needs the file `models/ldm/inpainting_big/last.ckpt` and I don't know where to get it.
> > > You can see in the script code that it wants a parameter `--in_dir` where you pass it a path to a folder that contains pairs of images named specially (i.e. 'example.png' and 'example_mask.png'). The mask has the part that you want to keep in black, and the rest in white. You can see example images here: https://github.com/CompVis/stable-diffusion/tree/main/data/inpainting_examples
> > > So, we only need that 'last.ckpt' file.
> > > Edit: With the provided download script it does get a zip in 'inpainting_big/', but it does not contain the 'last.ckpt'. Edit2: Found it in this repository (search for 'last'): https://github.com/pesser/stable-diffusion/blob/main/README.md
> > > Edit3: It works! You have to specify also the `--outdir` param, and optionally the `--steps` one. Edit4: Now I see this script only reconstructs the white parts based on the surroundings. It doesn't accept a prompt. I'm sorry.
> > 
> > 
> > Many thanks. I did not even know about the inplant mode.
> > I'm not familiar with image generation models, but reading through the script it appears that the masking information is encoded in the `conditioning` variable, while in generation mode the prompt is also encoded in the `conditioning` variable. Maybe the model must be trained in the way to accept two kinds of conditioning at the same time for this to work, so it's impossible now, I don't know.
> > I end up doing the following:
> > 
> > * run `img2img.py` with a large strength, which regenerates the whole image, hoping there is one result with at least similar background color
> > * crop the area containing the objects I am interested in, resize it and put it into the input image
> > * regenerate the modified input image with small strength, hoping the model will fix any artifacts
> > 
> > This approach has a main issue that the region of interest must be of relatively simple background, otherwise the artifacts will not be fixed well enough in the last step. The artifacts can turn into some weird "features" in the new image.
> > Guess this is the best we can do for now?
> > Edit: I found this on the reddit [https://www.reddit.com/r/StableDiffusion/comments/wyduk1/show_rstablediffusion_integrating_sd_in_photoshop/](url), at 0:28 the author indeed generate half of the image with a prompt and the other half unmodified. It's definitely doable while I have no idea how.
> 
> Take a look at this. It uses the diffusers library, but it seems to accomplish text-guided inpainting. https://colab.research.google.com/drive/1whhIiXxjQjbBuiq4lqwh-AlLIjh3l1OB

Took me quite a while to migrate from the official repo to huggingface's pipeline, but following this notebook it works like a charm.
